// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/amm.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AMMCreate - Creates an Automated Market Maker instance
// Reference: https://xrpl.org/ammcreate.html
type AMMCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset to deposit
	Amount *Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Second asset to deposit
	Amount2 *Amount `protobuf:"bytes,2,opt,name=amount2,proto3" json:"amount2,omitempty"`
	// Trading fee (0-1000, representing 0-1%)
	TradingFee    uint32 `protobuf:"varint,3,opt,name=trading_fee,json=tradingFee,proto3" json:"trading_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMCreate) Reset() {
	*x = AMMCreate{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMCreate) ProtoMessage() {}

func (x *AMMCreate) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMCreate.ProtoReflect.Descriptor instead.
func (*AMMCreate) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{0}
}

func (x *AMMCreate) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AMMCreate) GetAmount2() *Amount {
	if x != nil {
		return x.Amount2
	}
	return nil
}

func (x *AMMCreate) GetTradingFee() uint32 {
	if x != nil {
		return x.TradingFee
	}
	return 0
}

// AMMDeposit - Deposits assets into an AMM
// Reference: https://xrpl.org/ammdeposit.html
type AMMDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2 *Asset `protobuf:"bytes,2,opt,name=asset2,proto3" json:"asset2,omitempty"`
	// (Optional) Amount of first asset to deposit
	Amount *Amount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// (Optional) Amount of second asset to deposit
	Amount2 *Amount `protobuf:"bytes,4,opt,name=amount2,proto3" json:"amount2,omitempty"`
	// (Optional) Effective price for single-asset deposit
	EPrice *Amount `protobuf:"bytes,5,opt,name=e_price,json=ePrice,proto3" json:"e_price,omitempty"`
	// (Optional) LP tokens to receive
	LpTokenOut *Amount `protobuf:"bytes,6,opt,name=lp_token_out,json=lpTokenOut,proto3" json:"lp_token_out,omitempty"`
	// (Optional) Trading fee for the AMM
	TradingFee    uint32 `protobuf:"varint,7,opt,name=trading_fee,json=tradingFee,proto3" json:"trading_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMDeposit) Reset() {
	*x = AMMDeposit{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMDeposit) ProtoMessage() {}

func (x *AMMDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMDeposit.ProtoReflect.Descriptor instead.
func (*AMMDeposit) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{1}
}

func (x *AMMDeposit) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMDeposit) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

func (x *AMMDeposit) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AMMDeposit) GetAmount2() *Amount {
	if x != nil {
		return x.Amount2
	}
	return nil
}

func (x *AMMDeposit) GetEPrice() *Amount {
	if x != nil {
		return x.EPrice
	}
	return nil
}

func (x *AMMDeposit) GetLpTokenOut() *Amount {
	if x != nil {
		return x.LpTokenOut
	}
	return nil
}

func (x *AMMDeposit) GetTradingFee() uint32 {
	if x != nil {
		return x.TradingFee
	}
	return 0
}

// AMMWithdraw - Withdraws assets from an AMM
// Reference: https://xrpl.org/ammwithdraw.html
type AMMWithdraw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2 *Asset `protobuf:"bytes,2,opt,name=asset2,proto3" json:"asset2,omitempty"`
	// (Optional) Amount of first asset to withdraw
	Amount *Amount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// (Optional) Amount of second asset to withdraw
	Amount2 *Amount `protobuf:"bytes,4,opt,name=amount2,proto3" json:"amount2,omitempty"`
	// (Optional) Effective price for single-asset withdrawal
	EPrice *Amount `protobuf:"bytes,5,opt,name=e_price,json=ePrice,proto3" json:"e_price,omitempty"`
	// (Optional) LP tokens to burn
	LpTokenIn     *Amount `protobuf:"bytes,6,opt,name=lp_token_in,json=lpTokenIn,proto3" json:"lp_token_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMWithdraw) Reset() {
	*x = AMMWithdraw{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMWithdraw) ProtoMessage() {}

func (x *AMMWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMWithdraw.ProtoReflect.Descriptor instead.
func (*AMMWithdraw) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{2}
}

func (x *AMMWithdraw) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMWithdraw) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

func (x *AMMWithdraw) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AMMWithdraw) GetAmount2() *Amount {
	if x != nil {
		return x.Amount2
	}
	return nil
}

func (x *AMMWithdraw) GetEPrice() *Amount {
	if x != nil {
		return x.EPrice
	}
	return nil
}

func (x *AMMWithdraw) GetLpTokenIn() *Amount {
	if x != nil {
		return x.LpTokenIn
	}
	return nil
}

// AMMVote - Votes on the trading fee for an AMM
// Reference: https://xrpl.org/ammvote.html
type AMMVote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2 *Asset `protobuf:"bytes,2,opt,name=asset2,proto3" json:"asset2,omitempty"`
	// Proposed trading fee (0-1000)
	TradingFee    uint32 `protobuf:"varint,3,opt,name=trading_fee,json=tradingFee,proto3" json:"trading_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMVote) Reset() {
	*x = AMMVote{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMVote) ProtoMessage() {}

func (x *AMMVote) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMVote.ProtoReflect.Descriptor instead.
func (*AMMVote) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{3}
}

func (x *AMMVote) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMVote) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

func (x *AMMVote) GetTradingFee() uint32 {
	if x != nil {
		return x.TradingFee
	}
	return 0
}

// AMMBid - Bids on the auction slot of an AMM
// Reference: https://xrpl.org/ammbid.html
type AMMBid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2 *Asset `protobuf:"bytes,2,opt,name=asset2,proto3" json:"asset2,omitempty"`
	// (Optional) Minimum bid in LP tokens
	BidMin *Amount `protobuf:"bytes,3,opt,name=bid_min,json=bidMin,proto3" json:"bid_min,omitempty"`
	// (Optional) Maximum bid in LP tokens
	BidMax *Amount `protobuf:"bytes,4,opt,name=bid_max,json=bidMax,proto3" json:"bid_max,omitempty"`
	// (Optional) Accounts authorized to trade at discounted fee
	AuthAccounts  []*AuthAccount `protobuf:"bytes,5,rep,name=auth_accounts,json=authAccounts,proto3" json:"auth_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMBid) Reset() {
	*x = AMMBid{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMBid) ProtoMessage() {}

func (x *AMMBid) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMBid.ProtoReflect.Descriptor instead.
func (*AMMBid) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{4}
}

func (x *AMMBid) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMBid) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

func (x *AMMBid) GetBidMin() *Amount {
	if x != nil {
		return x.BidMin
	}
	return nil
}

func (x *AMMBid) GetBidMax() *Amount {
	if x != nil {
		return x.BidMax
	}
	return nil
}

func (x *AMMBid) GetAuthAccounts() []*AuthAccount {
	if x != nil {
		return x.AuthAccounts
	}
	return nil
}

type AuthAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAccount) Reset() {
	*x = AuthAccount{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAccount) ProtoMessage() {}

func (x *AuthAccount) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAccount.ProtoReflect.Descriptor instead.
func (*AuthAccount) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{5}
}

func (x *AuthAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// AMMDelete - Deletes an empty AMM instance
// Reference: https://xrpl.org/ammdelete.html
type AMMDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2        *Asset `protobuf:"bytes,2,opt,name=asset2,proto3" json:"asset2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMDelete) Reset() {
	*x = AMMDelete{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMDelete) ProtoMessage() {}

func (x *AMMDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMDelete.ProtoReflect.Descriptor instead.
func (*AMMDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{6}
}

func (x *AMMDelete) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMDelete) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

// AMMClawback - Claws back tokens from an AMM pool
// Reference: https://xrpl.org/ammclawback.html
type AMMClawback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Holder of the LP tokens
	Holder string `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	// First asset identifier
	Asset *Asset `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Second asset identifier
	Asset2 *Asset `protobuf:"bytes,3,opt,name=asset2,proto3" json:"asset2,omitempty"`
	// (Optional) Amount to claw back
	Amount        *Amount `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMMClawback) Reset() {
	*x = AMMClawback{}
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMClawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMClawback) ProtoMessage() {}

func (x *AMMClawback) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_amm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMClawback.ProtoReflect.Descriptor instead.
func (*AMMClawback) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_amm_proto_rawDescGZIP(), []int{7}
}

func (x *AMMClawback) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *AMMClawback) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AMMClawback) GetAsset2() *Asset {
	if x != nil {
		return x.Asset2
	}
	return nil
}

func (x *AMMClawback) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_sf_xrpl_type_v1_amm_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_amm_proto_rawDesc = "" +
	"\n" +
	"\x19sf/xrpl/type/v1/amm.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"\x90\x01\n" +
	"\tAMMCreate\x12/\n" +
	"\x06amount\x18\x01 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x121\n" +
	"\aamount2\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\aamount2\x12\x1f\n" +
	"\vtrading_fee\x18\x03 \x01(\rR\n" +
	"tradingFee\"\xdc\x02\n" +
	"\n" +
	"AMMDeposit\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\x12/\n" +
	"\x06amount\x18\x03 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x121\n" +
	"\aamount2\x18\x04 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\aamount2\x120\n" +
	"\ae_price\x18\x05 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06ePrice\x129\n" +
	"\flp_token_out\x18\x06 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\n" +
	"lpTokenOut\x12\x1f\n" +
	"\vtrading_fee\x18\a \x01(\rR\n" +
	"tradingFee\"\xba\x02\n" +
	"\vAMMWithdraw\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\x12/\n" +
	"\x06amount\x18\x03 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x121\n" +
	"\aamount2\x18\x04 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\aamount2\x120\n" +
	"\ae_price\x18\x05 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06ePrice\x127\n" +
	"\vlp_token_in\x18\x06 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\tlpTokenIn\"\x88\x01\n" +
	"\aAMMVote\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\x12\x1f\n" +
	"\vtrading_fee\x18\x03 \x01(\rR\n" +
	"tradingFee\"\x8d\x02\n" +
	"\x06AMMBid\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\x120\n" +
	"\abid_min\x18\x03 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06bidMin\x120\n" +
	"\abid_max\x18\x04 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06bidMax\x12A\n" +
	"\rauth_accounts\x18\x05 \x03(\v2\x1c.sf.xrpl.type.v1.AuthAccountR\fauthAccounts\"'\n" +
	"\vAuthAccount\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"i\n" +
	"\tAMMDelete\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\"\xb4\x01\n" +
	"\vAMMClawback\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12,\n" +
	"\x05asset\x18\x02 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12.\n" +
	"\x06asset2\x18\x03 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x06asset2\x12/\n" +
	"\x06amount\x18\x04 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amountBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_amm_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_amm_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_amm_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_amm_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_amm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_amm_proto_rawDesc), len(file_sf_xrpl_type_v1_amm_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_amm_proto_rawDescData
}

var file_sf_xrpl_type_v1_amm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sf_xrpl_type_v1_amm_proto_goTypes = []any{
	(*AMMCreate)(nil),   // 0: sf.xrpl.type.v1.AMMCreate
	(*AMMDeposit)(nil),  // 1: sf.xrpl.type.v1.AMMDeposit
	(*AMMWithdraw)(nil), // 2: sf.xrpl.type.v1.AMMWithdraw
	(*AMMVote)(nil),     // 3: sf.xrpl.type.v1.AMMVote
	(*AMMBid)(nil),      // 4: sf.xrpl.type.v1.AMMBid
	(*AuthAccount)(nil), // 5: sf.xrpl.type.v1.AuthAccount
	(*AMMDelete)(nil),   // 6: sf.xrpl.type.v1.AMMDelete
	(*AMMClawback)(nil), // 7: sf.xrpl.type.v1.AMMClawback
	(*Amount)(nil),      // 8: sf.xrpl.type.v1.Amount
	(*Asset)(nil),       // 9: sf.xrpl.type.v1.Asset
}
var file_sf_xrpl_type_v1_amm_proto_depIdxs = []int32{
	8,  // 0: sf.xrpl.type.v1.AMMCreate.amount:type_name -> sf.xrpl.type.v1.Amount
	8,  // 1: sf.xrpl.type.v1.AMMCreate.amount2:type_name -> sf.xrpl.type.v1.Amount
	9,  // 2: sf.xrpl.type.v1.AMMDeposit.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 3: sf.xrpl.type.v1.AMMDeposit.asset2:type_name -> sf.xrpl.type.v1.Asset
	8,  // 4: sf.xrpl.type.v1.AMMDeposit.amount:type_name -> sf.xrpl.type.v1.Amount
	8,  // 5: sf.xrpl.type.v1.AMMDeposit.amount2:type_name -> sf.xrpl.type.v1.Amount
	8,  // 6: sf.xrpl.type.v1.AMMDeposit.e_price:type_name -> sf.xrpl.type.v1.Amount
	8,  // 7: sf.xrpl.type.v1.AMMDeposit.lp_token_out:type_name -> sf.xrpl.type.v1.Amount
	9,  // 8: sf.xrpl.type.v1.AMMWithdraw.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 9: sf.xrpl.type.v1.AMMWithdraw.asset2:type_name -> sf.xrpl.type.v1.Asset
	8,  // 10: sf.xrpl.type.v1.AMMWithdraw.amount:type_name -> sf.xrpl.type.v1.Amount
	8,  // 11: sf.xrpl.type.v1.AMMWithdraw.amount2:type_name -> sf.xrpl.type.v1.Amount
	8,  // 12: sf.xrpl.type.v1.AMMWithdraw.e_price:type_name -> sf.xrpl.type.v1.Amount
	8,  // 13: sf.xrpl.type.v1.AMMWithdraw.lp_token_in:type_name -> sf.xrpl.type.v1.Amount
	9,  // 14: sf.xrpl.type.v1.AMMVote.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 15: sf.xrpl.type.v1.AMMVote.asset2:type_name -> sf.xrpl.type.v1.Asset
	9,  // 16: sf.xrpl.type.v1.AMMBid.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 17: sf.xrpl.type.v1.AMMBid.asset2:type_name -> sf.xrpl.type.v1.Asset
	8,  // 18: sf.xrpl.type.v1.AMMBid.bid_min:type_name -> sf.xrpl.type.v1.Amount
	8,  // 19: sf.xrpl.type.v1.AMMBid.bid_max:type_name -> sf.xrpl.type.v1.Amount
	5,  // 20: sf.xrpl.type.v1.AMMBid.auth_accounts:type_name -> sf.xrpl.type.v1.AuthAccount
	9,  // 21: sf.xrpl.type.v1.AMMDelete.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 22: sf.xrpl.type.v1.AMMDelete.asset2:type_name -> sf.xrpl.type.v1.Asset
	9,  // 23: sf.xrpl.type.v1.AMMClawback.asset:type_name -> sf.xrpl.type.v1.Asset
	9,  // 24: sf.xrpl.type.v1.AMMClawback.asset2:type_name -> sf.xrpl.type.v1.Asset
	8,  // 25: sf.xrpl.type.v1.AMMClawback.amount:type_name -> sf.xrpl.type.v1.Amount
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_amm_proto_init() }
func file_sf_xrpl_type_v1_amm_proto_init() {
	if File_sf_xrpl_type_v1_amm_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_amm_proto_rawDesc), len(file_sf_xrpl_type_v1_amm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_amm_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_amm_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_amm_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_amm_proto = out.File
	file_sf_xrpl_type_v1_amm_proto_goTypes = nil
	file_sf_xrpl_type_v1_amm_proto_depIdxs = nil
}
