// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/batch.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Batch - Submit multiple transactions atomically
// Reference: https://xrpl.org/batch.html
type Batch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of raw transactions to execute (minimum 2, maximum 8)
	RawTransactions []*RawTransaction `protobuf:"bytes,1,rep,name=raw_transactions,json=rawTransactions,proto3" json:"raw_transactions,omitempty"`
	// (Optional) Signatures for multi-account batch transactions
	BatchSigners []*BatchSigner `protobuf:"bytes,2,rep,name=batch_signers,json=batchSigners,proto3" json:"batch_signers,omitempty"`
	// Transaction flags for batch execution mode (required)
	// tfAllOrNothing = 65536 (0x00010000) - All transactions must succeed or batch fails
	// tfOnlyOne = 131072 (0x00020000) - Only first successful transaction is applied
	// tfUntilFailure = 262144 (0x00040000) - Apply until first failure, skip rest
	// tfIndependent = 524288 (0x00080000) - Apply all transactions regardless of failure
	Flags         uint32 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetRawTransactions() []*RawTransaction {
	if x != nil {
		return x.RawTransactions
	}
	return nil
}

func (x *Batch) GetBatchSigners() []*BatchSigner {
	if x != nil {
		return x.BatchSigners
	}
	return nil
}

func (x *Batch) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// RawTransaction - Inner transaction within a batch
type RawTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized transaction data (JSON encoded)
	// Must have tfInnerBatchTxn flag (1073741824 / 0x40000000)
	// Must have Fee = "0"
	// Must have SigningPubKey = ""
	// Must not have TxnSignature
	RawTransaction []byte `protobuf:"bytes,1,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RawTransaction) Reset() {
	*x = RawTransaction{}
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTransaction) ProtoMessage() {}

func (x *RawTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTransaction.ProtoReflect.Descriptor instead.
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_batch_proto_rawDescGZIP(), []int{1}
}

func (x *RawTransaction) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

// BatchSigner - Signature for an account in multi-account batch
type BatchSigner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account with at least one inner transaction
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// (Optional) Hex representation of public key
	SigningPubKey string `protobuf:"bytes,2,opt,name=signing_pub_key,json=signingPubKey,proto3" json:"signing_pub_key,omitempty"`
	// (Optional) Signature from this account
	TxnSignature string `protobuf:"bytes,3,opt,name=txn_signature,json=txnSignature,proto3" json:"txn_signature,omitempty"`
	// (Optional) Multi-signature array (alternative to single signature)
	// Uses the Signer message type defined in signer.proto
	Signers       []*Signer `protobuf:"bytes,4,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSigner) Reset() {
	*x = BatchSigner{}
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSigner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSigner) ProtoMessage() {}

func (x *BatchSigner) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSigner.ProtoReflect.Descriptor instead.
func (*BatchSigner) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_batch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchSigner) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BatchSigner) GetSigningPubKey() string {
	if x != nil {
		return x.SigningPubKey
	}
	return ""
}

func (x *BatchSigner) GetTxnSignature() string {
	if x != nil {
		return x.TxnSignature
	}
	return ""
}

func (x *BatchSigner) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

var File_sf_xrpl_type_v1_batch_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_batch_proto_rawDesc = "" +
	"\n" +
	"\x1bsf/xrpl/type/v1/batch.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/signer.proto\"\xac\x01\n" +
	"\x05Batch\x12J\n" +
	"\x10raw_transactions\x18\x01 \x03(\v2\x1f.sf.xrpl.type.v1.RawTransactionR\x0frawTransactions\x12A\n" +
	"\rbatch_signers\x18\x02 \x03(\v2\x1c.sf.xrpl.type.v1.BatchSignerR\fbatchSigners\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\"9\n" +
	"\x0eRawTransaction\x12'\n" +
	"\x0fraw_transaction\x18\x01 \x01(\fR\x0erawTransaction\"\xa7\x01\n" +
	"\vBatchSigner\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12&\n" +
	"\x0fsigning_pub_key\x18\x02 \x01(\tR\rsigningPubKey\x12#\n" +
	"\rtxn_signature\x18\x03 \x01(\tR\ftxnSignature\x121\n" +
	"\asigners\x18\x04 \x03(\v2\x17.sf.xrpl.type.v1.SignerR\asignersBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_batch_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_batch_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_batch_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_batch_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_batch_proto_rawDesc), len(file_sf_xrpl_type_v1_batch_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_batch_proto_rawDescData
}

var file_sf_xrpl_type_v1_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_xrpl_type_v1_batch_proto_goTypes = []any{
	(*Batch)(nil),          // 0: sf.xrpl.type.v1.Batch
	(*RawTransaction)(nil), // 1: sf.xrpl.type.v1.RawTransaction
	(*BatchSigner)(nil),    // 2: sf.xrpl.type.v1.BatchSigner
	(*Signer)(nil),         // 3: sf.xrpl.type.v1.Signer
}
var file_sf_xrpl_type_v1_batch_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.Batch.raw_transactions:type_name -> sf.xrpl.type.v1.RawTransaction
	2, // 1: sf.xrpl.type.v1.Batch.batch_signers:type_name -> sf.xrpl.type.v1.BatchSigner
	3, // 2: sf.xrpl.type.v1.BatchSigner.signers:type_name -> sf.xrpl.type.v1.Signer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_batch_proto_init() }
func file_sf_xrpl_type_v1_batch_proto_init() {
	if File_sf_xrpl_type_v1_batch_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_signer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_batch_proto_rawDesc), len(file_sf_xrpl_type_v1_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_batch_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_batch_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_batch_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_batch_proto = out.File
	file_sf_xrpl_type_v1_batch_proto_goTypes = nil
	file_sf_xrpl_type_v1_batch_proto_depIdxs = nil
}
