// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/block.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block represents an XRPL validated ledger
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger sequence number (ledger_index)
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Ledger hash (32 bytes)
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Ledger header information
	Header *Header `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	// Schema version for this protobuf
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Transactions in this ledger
	Transactions []*Transaction `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Ledger close time
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent ledger hash
	ParentHash []byte `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// Total XRP in drops (int64 for 10^17 max)
	TotalDrops int64 `protobuf:"varint,2,opt,name=total_drops,json=totalDrops,proto3" json:"total_drops,omitempty"`
	// Account state hash (state tree root)
	AccountHash []byte `protobuf:"bytes,3,opt,name=account_hash,json=accountHash,proto3" json:"account_hash,omitempty"`
	// Transaction tree hash
	TransactionHash []byte `protobuf:"bytes,4,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	// Close time resolution in seconds
	CloseTimeResolution uint32 `protobuf:"varint,5,opt,name=close_time_resolution,json=closeTimeResolution,proto3" json:"close_time_resolution,omitempty"`
	// Close flags
	CloseFlags    uint32 `protobuf:"varint,6,opt,name=close_flags,json=closeFlags,proto3" json:"close_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_block_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Header) GetTotalDrops() int64 {
	if x != nil {
		return x.TotalDrops
	}
	return 0
}

func (x *Header) GetAccountHash() []byte {
	if x != nil {
		return x.AccountHash
	}
	return nil
}

func (x *Header) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *Header) GetCloseTimeResolution() uint32 {
	if x != nil {
		return x.CloseTimeResolution
	}
	return 0
}

func (x *Header) GetCloseFlags() uint32 {
	if x != nil {
		return x.CloseFlags
	}
	return 0
}

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction hash (32 bytes)
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Transaction result code (e.g., "tesSUCCESS", "tecPATH_DRY", "temMALFORMED")
	// Future-proof: supports any result code XRPL adds without schema updates
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// Position in ledger (0-indexed)
	Index uint32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Raw transaction blob (XRPL binary format)
	// Kept for backward compatibility and advanced decoding
	TxBlob []byte `protobuf:"bytes,4,opt,name=tx_blob,json=txBlob,proto3" json:"tx_blob,omitempty"`
	// Transaction metadata blob (XRPL binary format)
	// Contains: AffectedNodes, delivered_amount, etc.
	MetaBlob []byte `protobuf:"bytes,5,opt,name=meta_blob,json=metaBlob,proto3" json:"meta_blob,omitempty"`
	// Transaction type string (e.g., "Payment", "OfferCreate", "NFTokenMint")
	// Future-proof: supports any transaction type XRPL adds without schema
	// updates
	TxType string `protobuf:"bytes,6,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	// Account that initiated this transaction
	Account string `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	// Fee paid in drops
	Fee uint64 `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	// Transaction sequence number
	Sequence uint32 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Hash value identifying another transaction. If provided, this transaction
	// is only valid if the sending account's previously-sent transaction matches
	// the provided hash.
	AccountTxnId string `protobuf:"bytes,10,opt,name=account_txn_id,json=accountTxnId,proto3" json:"account_txn_id,omitempty"`
	// Delegate account that is sending the transaction on behalf of the Account
	Delegate string `protobuf:"bytes,11,opt,name=delegate,proto3" json:"delegate,omitempty"`
	// Set of bit-flags for this transaction
	Flags uint32 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`
	// Highest ledger index this transaction can appear in
	LastLedgerSequence uint32 `protobuf:"varint,13,opt,name=last_ledger_sequence,json=lastLedgerSequence,proto3" json:"last_ledger_sequence,omitempty"`
	// Additional arbitrary information attached to this transaction
	Memos []*Memo `protobuf:"bytes,14,rep,name=memos,proto3" json:"memos,omitempty"`
	// Network ID of the chain this transaction is intended for
	// Required for networks with ID >= 1025, disallowed for ID <= 1024
	NetworkId uint32 `protobuf:"varint,15,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Multi-signature data (for multi-signed transactions)
	Signers []*Signer `protobuf:"bytes,16,rep,name=signers,proto3" json:"signers,omitempty"`
	// Arbitrary integer used to identify the reason for this payment
	SourceTag uint32 `protobuf:"varint,17,opt,name=source_tag,json=sourceTag,proto3" json:"source_tag,omitempty"`
	// Public key that corresponds to the private key used to sign this
	// transaction Empty string indicates a multi-signature is present in the
	// signers field
	SigningPubKey string `protobuf:"bytes,18,opt,name=signing_pub_key,json=signingPubKey,proto3" json:"signing_pub_key,omitempty"`
	// Sequence number of the ticket to use in place of a Sequence number
	// If provided, Sequence must be 0
	TicketSequence uint32 `protobuf:"varint,19,opt,name=ticket_sequence,json=ticketSequence,proto3" json:"ticket_sequence,omitempty"`
	// Signature that verifies this transaction as originating from the account
	TxnSignature string `protobuf:"bytes,20,opt,name=txn_signature,json=txnSignature,proto3" json:"txn_signature,omitempty"`
	// Decoded transaction details based on tx_type
	//
	// Types that are valid to be assigned to TxDetails:
	//
	//	*Transaction_Payment
	//	*Transaction_OfferCreate
	//	*Transaction_OfferCancel
	//	*Transaction_TrustSet
	//	*Transaction_AccountSet
	//	*Transaction_AccountDelete
	//	*Transaction_SetRegularKey
	//	*Transaction_SignerListSet
	//	*Transaction_EscrowCreate
	//	*Transaction_EscrowFinish
	//	*Transaction_EscrowCancel
	//	*Transaction_PaymentChannelCreate
	//	*Transaction_PaymentChannelFund
	//	*Transaction_PaymentChannelClaim
	//	*Transaction_CheckCreate
	//	*Transaction_CheckCash
	//	*Transaction_CheckCancel
	//	*Transaction_DepositPreauth
	//	*Transaction_TicketCreate
	//	*Transaction_NftokenMint
	//	*Transaction_NftokenBurn
	//	*Transaction_NftokenCreateOffer
	//	*Transaction_NftokenCancelOffer
	//	*Transaction_NftokenAcceptOffer
	//	*Transaction_NftokenModify
	//	*Transaction_Clawback
	//	*Transaction_AmmCreate
	//	*Transaction_AmmDeposit
	//	*Transaction_AmmWithdraw
	//	*Transaction_AmmVote
	//	*Transaction_AmmBid
	//	*Transaction_AmmDelete
	//	*Transaction_AmmClawback
	//	*Transaction_XchainCreateBridge
	//	*Transaction_XchainModifyBridge
	//	*Transaction_XchainCreateClaimId
	//	*Transaction_XchainCommit
	//	*Transaction_XchainClaim
	//	*Transaction_XchainAccountCreateCommit
	//	*Transaction_XchainAddClaimAttestation
	//	*Transaction_XchainAddAccountCreateAttestation
	//	*Transaction_DidSet
	//	*Transaction_DidDelete
	//	*Transaction_OracleSet
	//	*Transaction_OracleDelete
	//	*Transaction_MptokenIssuanceCreate
	//	*Transaction_MptokenIssuanceDestroy
	//	*Transaction_MptokenIssuanceSet
	//	*Transaction_MptokenAuthorize
	//	*Transaction_CredentialCreate
	//	*Transaction_CredentialAccept
	//	*Transaction_CredentialDelete
	//	*Transaction_PermissionedDomainSet
	//	*Transaction_PermissionedDomainDelete
	//	*Transaction_DelegateSet
	//	*Transaction_Batch
	//	*Transaction_EnableAmendment
	//	*Transaction_SetFee
	//	*Transaction_UnlModify
	//	*Transaction_LedgerStateFix
	TxDetails     isTransaction_TxDetails `protobuf_oneof:"tx_details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_block_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Transaction) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Transaction) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Transaction) GetTxBlob() []byte {
	if x != nil {
		return x.TxBlob
	}
	return nil
}

func (x *Transaction) GetMetaBlob() []byte {
	if x != nil {
		return x.MetaBlob
	}
	return nil
}

func (x *Transaction) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

func (x *Transaction) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Transaction) GetAccountTxnId() string {
	if x != nil {
		return x.AccountTxnId
	}
	return ""
}

func (x *Transaction) GetDelegate() string {
	if x != nil {
		return x.Delegate
	}
	return ""
}

func (x *Transaction) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Transaction) GetLastLedgerSequence() uint32 {
	if x != nil {
		return x.LastLedgerSequence
	}
	return 0
}

func (x *Transaction) GetMemos() []*Memo {
	if x != nil {
		return x.Memos
	}
	return nil
}

func (x *Transaction) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

func (x *Transaction) GetSourceTag() uint32 {
	if x != nil {
		return x.SourceTag
	}
	return 0
}

func (x *Transaction) GetSigningPubKey() string {
	if x != nil {
		return x.SigningPubKey
	}
	return ""
}

func (x *Transaction) GetTicketSequence() uint32 {
	if x != nil {
		return x.TicketSequence
	}
	return 0
}

func (x *Transaction) GetTxnSignature() string {
	if x != nil {
		return x.TxnSignature
	}
	return ""
}

func (x *Transaction) GetTxDetails() isTransaction_TxDetails {
	if x != nil {
		return x.TxDetails
	}
	return nil
}

func (x *Transaction) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *Transaction) GetOfferCreate() *OfferCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_OfferCreate); ok {
			return x.OfferCreate
		}
	}
	return nil
}

func (x *Transaction) GetOfferCancel() *OfferCancel {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_OfferCancel); ok {
			return x.OfferCancel
		}
	}
	return nil
}

func (x *Transaction) GetTrustSet() *TrustSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_TrustSet); ok {
			return x.TrustSet
		}
	}
	return nil
}

func (x *Transaction) GetAccountSet() *AccountSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AccountSet); ok {
			return x.AccountSet
		}
	}
	return nil
}

func (x *Transaction) GetAccountDelete() *AccountDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AccountDelete); ok {
			return x.AccountDelete
		}
	}
	return nil
}

func (x *Transaction) GetSetRegularKey() *SetRegularKey {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_SetRegularKey); ok {
			return x.SetRegularKey
		}
	}
	return nil
}

func (x *Transaction) GetSignerListSet() *SignerListSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_SignerListSet); ok {
			return x.SignerListSet
		}
	}
	return nil
}

func (x *Transaction) GetEscrowCreate() *EscrowCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_EscrowCreate); ok {
			return x.EscrowCreate
		}
	}
	return nil
}

func (x *Transaction) GetEscrowFinish() *EscrowFinish {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_EscrowFinish); ok {
			return x.EscrowFinish
		}
	}
	return nil
}

func (x *Transaction) GetEscrowCancel() *EscrowCancel {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_EscrowCancel); ok {
			return x.EscrowCancel
		}
	}
	return nil
}

func (x *Transaction) GetPaymentChannelCreate() *PaymentChannelCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_PaymentChannelCreate); ok {
			return x.PaymentChannelCreate
		}
	}
	return nil
}

func (x *Transaction) GetPaymentChannelFund() *PaymentChannelFund {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_PaymentChannelFund); ok {
			return x.PaymentChannelFund
		}
	}
	return nil
}

func (x *Transaction) GetPaymentChannelClaim() *PaymentChannelClaim {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_PaymentChannelClaim); ok {
			return x.PaymentChannelClaim
		}
	}
	return nil
}

func (x *Transaction) GetCheckCreate() *CheckCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CheckCreate); ok {
			return x.CheckCreate
		}
	}
	return nil
}

func (x *Transaction) GetCheckCash() *CheckCash {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CheckCash); ok {
			return x.CheckCash
		}
	}
	return nil
}

func (x *Transaction) GetCheckCancel() *CheckCancel {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CheckCancel); ok {
			return x.CheckCancel
		}
	}
	return nil
}

func (x *Transaction) GetDepositPreauth() *DepositPreauth {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_DepositPreauth); ok {
			return x.DepositPreauth
		}
	}
	return nil
}

func (x *Transaction) GetTicketCreate() *TicketCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_TicketCreate); ok {
			return x.TicketCreate
		}
	}
	return nil
}

func (x *Transaction) GetNftokenMint() *NFTokenMint {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenMint); ok {
			return x.NftokenMint
		}
	}
	return nil
}

func (x *Transaction) GetNftokenBurn() *NFTokenBurn {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenBurn); ok {
			return x.NftokenBurn
		}
	}
	return nil
}

func (x *Transaction) GetNftokenCreateOffer() *NFTokenCreateOffer {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenCreateOffer); ok {
			return x.NftokenCreateOffer
		}
	}
	return nil
}

func (x *Transaction) GetNftokenCancelOffer() *NFTokenCancelOffer {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenCancelOffer); ok {
			return x.NftokenCancelOffer
		}
	}
	return nil
}

func (x *Transaction) GetNftokenAcceptOffer() *NFTokenAcceptOffer {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenAcceptOffer); ok {
			return x.NftokenAcceptOffer
		}
	}
	return nil
}

func (x *Transaction) GetNftokenModify() *NFTokenModify {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_NftokenModify); ok {
			return x.NftokenModify
		}
	}
	return nil
}

func (x *Transaction) GetClawback() *Clawback {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_Clawback); ok {
			return x.Clawback
		}
	}
	return nil
}

func (x *Transaction) GetAmmCreate() *AMMCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmCreate); ok {
			return x.AmmCreate
		}
	}
	return nil
}

func (x *Transaction) GetAmmDeposit() *AMMDeposit {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmDeposit); ok {
			return x.AmmDeposit
		}
	}
	return nil
}

func (x *Transaction) GetAmmWithdraw() *AMMWithdraw {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmWithdraw); ok {
			return x.AmmWithdraw
		}
	}
	return nil
}

func (x *Transaction) GetAmmVote() *AMMVote {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmVote); ok {
			return x.AmmVote
		}
	}
	return nil
}

func (x *Transaction) GetAmmBid() *AMMBid {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmBid); ok {
			return x.AmmBid
		}
	}
	return nil
}

func (x *Transaction) GetAmmDelete() *AMMDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmDelete); ok {
			return x.AmmDelete
		}
	}
	return nil
}

func (x *Transaction) GetAmmClawback() *AMMClawback {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_AmmClawback); ok {
			return x.AmmClawback
		}
	}
	return nil
}

func (x *Transaction) GetXchainCreateBridge() *XChainCreateBridge {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainCreateBridge); ok {
			return x.XchainCreateBridge
		}
	}
	return nil
}

func (x *Transaction) GetXchainModifyBridge() *XChainModifyBridge {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainModifyBridge); ok {
			return x.XchainModifyBridge
		}
	}
	return nil
}

func (x *Transaction) GetXchainCreateClaimId() *XChainCreateClaimID {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainCreateClaimId); ok {
			return x.XchainCreateClaimId
		}
	}
	return nil
}

func (x *Transaction) GetXchainCommit() *XChainCommit {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainCommit); ok {
			return x.XchainCommit
		}
	}
	return nil
}

func (x *Transaction) GetXchainClaim() *XChainClaim {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainClaim); ok {
			return x.XchainClaim
		}
	}
	return nil
}

func (x *Transaction) GetXchainAccountCreateCommit() *XChainAccountCreateCommit {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainAccountCreateCommit); ok {
			return x.XchainAccountCreateCommit
		}
	}
	return nil
}

func (x *Transaction) GetXchainAddClaimAttestation() *XChainAddClaimAttestation {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainAddClaimAttestation); ok {
			return x.XchainAddClaimAttestation
		}
	}
	return nil
}

func (x *Transaction) GetXchainAddAccountCreateAttestation() *XChainAddAccountCreateAttestation {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_XchainAddAccountCreateAttestation); ok {
			return x.XchainAddAccountCreateAttestation
		}
	}
	return nil
}

func (x *Transaction) GetDidSet() *DIDSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_DidSet); ok {
			return x.DidSet
		}
	}
	return nil
}

func (x *Transaction) GetDidDelete() *DIDDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_DidDelete); ok {
			return x.DidDelete
		}
	}
	return nil
}

func (x *Transaction) GetOracleSet() *OracleSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_OracleSet); ok {
			return x.OracleSet
		}
	}
	return nil
}

func (x *Transaction) GetOracleDelete() *OracleDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_OracleDelete); ok {
			return x.OracleDelete
		}
	}
	return nil
}

func (x *Transaction) GetMptokenIssuanceCreate() *MPTokenIssuanceCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_MptokenIssuanceCreate); ok {
			return x.MptokenIssuanceCreate
		}
	}
	return nil
}

func (x *Transaction) GetMptokenIssuanceDestroy() *MPTokenIssuanceDestroy {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_MptokenIssuanceDestroy); ok {
			return x.MptokenIssuanceDestroy
		}
	}
	return nil
}

func (x *Transaction) GetMptokenIssuanceSet() *MPTokenIssuanceSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_MptokenIssuanceSet); ok {
			return x.MptokenIssuanceSet
		}
	}
	return nil
}

func (x *Transaction) GetMptokenAuthorize() *MPTokenAuthorize {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_MptokenAuthorize); ok {
			return x.MptokenAuthorize
		}
	}
	return nil
}

func (x *Transaction) GetCredentialCreate() *CredentialCreate {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CredentialCreate); ok {
			return x.CredentialCreate
		}
	}
	return nil
}

func (x *Transaction) GetCredentialAccept() *CredentialAccept {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CredentialAccept); ok {
			return x.CredentialAccept
		}
	}
	return nil
}

func (x *Transaction) GetCredentialDelete() *CredentialDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_CredentialDelete); ok {
			return x.CredentialDelete
		}
	}
	return nil
}

func (x *Transaction) GetPermissionedDomainSet() *PermissionedDomainSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_PermissionedDomainSet); ok {
			return x.PermissionedDomainSet
		}
	}
	return nil
}

func (x *Transaction) GetPermissionedDomainDelete() *PermissionedDomainDelete {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_PermissionedDomainDelete); ok {
			return x.PermissionedDomainDelete
		}
	}
	return nil
}

func (x *Transaction) GetDelegateSet() *DelegateSet {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_DelegateSet); ok {
			return x.DelegateSet
		}
	}
	return nil
}

func (x *Transaction) GetBatch() *Batch {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *Transaction) GetEnableAmendment() *EnableAmendment {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_EnableAmendment); ok {
			return x.EnableAmendment
		}
	}
	return nil
}

func (x *Transaction) GetSetFee() *SetFee {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_SetFee); ok {
			return x.SetFee
		}
	}
	return nil
}

func (x *Transaction) GetUnlModify() *UNLModify {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_UnlModify); ok {
			return x.UnlModify
		}
	}
	return nil
}

func (x *Transaction) GetLedgerStateFix() *LedgerStateFix {
	if x != nil {
		if x, ok := x.TxDetails.(*Transaction_LedgerStateFix); ok {
			return x.LedgerStateFix
		}
	}
	return nil
}

type isTransaction_TxDetails interface {
	isTransaction_TxDetails()
}

type Transaction_Payment struct {
	// Payment transactions
	Payment *Payment `protobuf:"bytes,30,opt,name=payment,proto3,oneof"`
}

type Transaction_OfferCreate struct {
	// DEX transactions
	OfferCreate *OfferCreate `protobuf:"bytes,31,opt,name=offer_create,json=offerCreate,proto3,oneof"`
}

type Transaction_OfferCancel struct {
	OfferCancel *OfferCancel `protobuf:"bytes,32,opt,name=offer_cancel,json=offerCancel,proto3,oneof"`
}

type Transaction_TrustSet struct {
	// Trustline
	TrustSet *TrustSet `protobuf:"bytes,33,opt,name=trust_set,json=trustSet,proto3,oneof"`
}

type Transaction_AccountSet struct {
	// Account management
	AccountSet *AccountSet `protobuf:"bytes,34,opt,name=account_set,json=accountSet,proto3,oneof"`
}

type Transaction_AccountDelete struct {
	AccountDelete *AccountDelete `protobuf:"bytes,35,opt,name=account_delete,json=accountDelete,proto3,oneof"`
}

type Transaction_SetRegularKey struct {
	SetRegularKey *SetRegularKey `protobuf:"bytes,36,opt,name=set_regular_key,json=setRegularKey,proto3,oneof"`
}

type Transaction_SignerListSet struct {
	SignerListSet *SignerListSet `protobuf:"bytes,37,opt,name=signer_list_set,json=signerListSet,proto3,oneof"`
}

type Transaction_EscrowCreate struct {
	// Escrow
	EscrowCreate *EscrowCreate `protobuf:"bytes,40,opt,name=escrow_create,json=escrowCreate,proto3,oneof"`
}

type Transaction_EscrowFinish struct {
	EscrowFinish *EscrowFinish `protobuf:"bytes,41,opt,name=escrow_finish,json=escrowFinish,proto3,oneof"`
}

type Transaction_EscrowCancel struct {
	EscrowCancel *EscrowCancel `protobuf:"bytes,42,opt,name=escrow_cancel,json=escrowCancel,proto3,oneof"`
}

type Transaction_PaymentChannelCreate struct {
	// Payment channels
	PaymentChannelCreate *PaymentChannelCreate `protobuf:"bytes,43,opt,name=payment_channel_create,json=paymentChannelCreate,proto3,oneof"`
}

type Transaction_PaymentChannelFund struct {
	PaymentChannelFund *PaymentChannelFund `protobuf:"bytes,44,opt,name=payment_channel_fund,json=paymentChannelFund,proto3,oneof"`
}

type Transaction_PaymentChannelClaim struct {
	PaymentChannelClaim *PaymentChannelClaim `protobuf:"bytes,45,opt,name=payment_channel_claim,json=paymentChannelClaim,proto3,oneof"`
}

type Transaction_CheckCreate struct {
	// Checks
	CheckCreate *CheckCreate `protobuf:"bytes,46,opt,name=check_create,json=checkCreate,proto3,oneof"`
}

type Transaction_CheckCash struct {
	CheckCash *CheckCash `protobuf:"bytes,47,opt,name=check_cash,json=checkCash,proto3,oneof"`
}

type Transaction_CheckCancel struct {
	CheckCancel *CheckCancel `protobuf:"bytes,48,opt,name=check_cancel,json=checkCancel,proto3,oneof"`
}

type Transaction_DepositPreauth struct {
	// Other account features
	DepositPreauth *DepositPreauth `protobuf:"bytes,49,opt,name=deposit_preauth,json=depositPreauth,proto3,oneof"`
}

type Transaction_TicketCreate struct {
	TicketCreate *TicketCreate `protobuf:"bytes,50,opt,name=ticket_create,json=ticketCreate,proto3,oneof"`
}

type Transaction_NftokenMint struct {
	// NFT transactions
	NftokenMint *NFTokenMint `protobuf:"bytes,60,opt,name=nftoken_mint,json=nftokenMint,proto3,oneof"`
}

type Transaction_NftokenBurn struct {
	NftokenBurn *NFTokenBurn `protobuf:"bytes,61,opt,name=nftoken_burn,json=nftokenBurn,proto3,oneof"`
}

type Transaction_NftokenCreateOffer struct {
	NftokenCreateOffer *NFTokenCreateOffer `protobuf:"bytes,62,opt,name=nftoken_create_offer,json=nftokenCreateOffer,proto3,oneof"`
}

type Transaction_NftokenCancelOffer struct {
	NftokenCancelOffer *NFTokenCancelOffer `protobuf:"bytes,63,opt,name=nftoken_cancel_offer,json=nftokenCancelOffer,proto3,oneof"`
}

type Transaction_NftokenAcceptOffer struct {
	NftokenAcceptOffer *NFTokenAcceptOffer `protobuf:"bytes,64,opt,name=nftoken_accept_offer,json=nftokenAcceptOffer,proto3,oneof"`
}

type Transaction_NftokenModify struct {
	NftokenModify *NFTokenModify `protobuf:"bytes,65,opt,name=nftoken_modify,json=nftokenModify,proto3,oneof"`
}

type Transaction_Clawback struct {
	// Clawback
	Clawback *Clawback `protobuf:"bytes,70,opt,name=clawback,proto3,oneof"`
}

type Transaction_AmmCreate struct {
	// AMM transactions
	AmmCreate *AMMCreate `protobuf:"bytes,80,opt,name=amm_create,json=ammCreate,proto3,oneof"`
}

type Transaction_AmmDeposit struct {
	AmmDeposit *AMMDeposit `protobuf:"bytes,81,opt,name=amm_deposit,json=ammDeposit,proto3,oneof"`
}

type Transaction_AmmWithdraw struct {
	AmmWithdraw *AMMWithdraw `protobuf:"bytes,82,opt,name=amm_withdraw,json=ammWithdraw,proto3,oneof"`
}

type Transaction_AmmVote struct {
	AmmVote *AMMVote `protobuf:"bytes,83,opt,name=amm_vote,json=ammVote,proto3,oneof"`
}

type Transaction_AmmBid struct {
	AmmBid *AMMBid `protobuf:"bytes,84,opt,name=amm_bid,json=ammBid,proto3,oneof"`
}

type Transaction_AmmDelete struct {
	AmmDelete *AMMDelete `protobuf:"bytes,85,opt,name=amm_delete,json=ammDelete,proto3,oneof"`
}

type Transaction_AmmClawback struct {
	AmmClawback *AMMClawback `protobuf:"bytes,86,opt,name=amm_clawback,json=ammClawback,proto3,oneof"`
}

type Transaction_XchainCreateBridge struct {
	// Cross-chain bridge transactions
	XchainCreateBridge *XChainCreateBridge `protobuf:"bytes,90,opt,name=xchain_create_bridge,json=xchainCreateBridge,proto3,oneof"`
}

type Transaction_XchainModifyBridge struct {
	XchainModifyBridge *XChainModifyBridge `protobuf:"bytes,91,opt,name=xchain_modify_bridge,json=xchainModifyBridge,proto3,oneof"`
}

type Transaction_XchainCreateClaimId struct {
	XchainCreateClaimId *XChainCreateClaimID `protobuf:"bytes,92,opt,name=xchain_create_claim_id,json=xchainCreateClaimId,proto3,oneof"`
}

type Transaction_XchainCommit struct {
	XchainCommit *XChainCommit `protobuf:"bytes,93,opt,name=xchain_commit,json=xchainCommit,proto3,oneof"`
}

type Transaction_XchainClaim struct {
	XchainClaim *XChainClaim `protobuf:"bytes,94,opt,name=xchain_claim,json=xchainClaim,proto3,oneof"`
}

type Transaction_XchainAccountCreateCommit struct {
	XchainAccountCreateCommit *XChainAccountCreateCommit `protobuf:"bytes,95,opt,name=xchain_account_create_commit,json=xchainAccountCreateCommit,proto3,oneof"`
}

type Transaction_XchainAddClaimAttestation struct {
	XchainAddClaimAttestation *XChainAddClaimAttestation `protobuf:"bytes,96,opt,name=xchain_add_claim_attestation,json=xchainAddClaimAttestation,proto3,oneof"`
}

type Transaction_XchainAddAccountCreateAttestation struct {
	XchainAddAccountCreateAttestation *XChainAddAccountCreateAttestation `protobuf:"bytes,97,opt,name=xchain_add_account_create_attestation,json=xchainAddAccountCreateAttestation,proto3,oneof"`
}

type Transaction_DidSet struct {
	// DID transactions
	DidSet *DIDSet `protobuf:"bytes,100,opt,name=did_set,json=didSet,proto3,oneof"`
}

type Transaction_DidDelete struct {
	DidDelete *DIDDelete `protobuf:"bytes,101,opt,name=did_delete,json=didDelete,proto3,oneof"`
}

type Transaction_OracleSet struct {
	// Oracle transactions
	OracleSet *OracleSet `protobuf:"bytes,102,opt,name=oracle_set,json=oracleSet,proto3,oneof"`
}

type Transaction_OracleDelete struct {
	OracleDelete *OracleDelete `protobuf:"bytes,103,opt,name=oracle_delete,json=oracleDelete,proto3,oneof"`
}

type Transaction_MptokenIssuanceCreate struct {
	// MPToken transactions
	MptokenIssuanceCreate *MPTokenIssuanceCreate `protobuf:"bytes,110,opt,name=mptoken_issuance_create,json=mptokenIssuanceCreate,proto3,oneof"`
}

type Transaction_MptokenIssuanceDestroy struct {
	MptokenIssuanceDestroy *MPTokenIssuanceDestroy `protobuf:"bytes,111,opt,name=mptoken_issuance_destroy,json=mptokenIssuanceDestroy,proto3,oneof"`
}

type Transaction_MptokenIssuanceSet struct {
	MptokenIssuanceSet *MPTokenIssuanceSet `protobuf:"bytes,112,opt,name=mptoken_issuance_set,json=mptokenIssuanceSet,proto3,oneof"`
}

type Transaction_MptokenAuthorize struct {
	MptokenAuthorize *MPTokenAuthorize `protobuf:"bytes,113,opt,name=mptoken_authorize,json=mptokenAuthorize,proto3,oneof"`
}

type Transaction_CredentialCreate struct {
	// Credential transactions
	CredentialCreate *CredentialCreate `protobuf:"bytes,120,opt,name=credential_create,json=credentialCreate,proto3,oneof"`
}

type Transaction_CredentialAccept struct {
	CredentialAccept *CredentialAccept `protobuf:"bytes,121,opt,name=credential_accept,json=credentialAccept,proto3,oneof"`
}

type Transaction_CredentialDelete struct {
	CredentialDelete *CredentialDelete `protobuf:"bytes,122,opt,name=credential_delete,json=credentialDelete,proto3,oneof"`
}

type Transaction_PermissionedDomainSet struct {
	// Permissioned domain transactions
	PermissionedDomainSet *PermissionedDomainSet `protobuf:"bytes,130,opt,name=permissioned_domain_set,json=permissionedDomainSet,proto3,oneof"`
}

type Transaction_PermissionedDomainDelete struct {
	PermissionedDomainDelete *PermissionedDomainDelete `protobuf:"bytes,131,opt,name=permissioned_domain_delete,json=permissionedDomainDelete,proto3,oneof"`
}

type Transaction_DelegateSet struct {
	// Delegate transactions
	DelegateSet *DelegateSet `protobuf:"bytes,132,opt,name=delegate_set,json=delegateSet,proto3,oneof"`
}

type Transaction_Batch struct {
	// Batch transaction
	Batch *Batch `protobuf:"bytes,133,opt,name=batch,proto3,oneof"`
}

type Transaction_EnableAmendment struct {
	// System transactions (pseudo-transactions)
	EnableAmendment *EnableAmendment `protobuf:"bytes,900,opt,name=enable_amendment,json=enableAmendment,proto3,oneof"`
}

type Transaction_SetFee struct {
	SetFee *SetFee `protobuf:"bytes,901,opt,name=set_fee,json=setFee,proto3,oneof"`
}

type Transaction_UnlModify struct {
	UnlModify *UNLModify `protobuf:"bytes,902,opt,name=unl_modify,json=unlModify,proto3,oneof"`
}

type Transaction_LedgerStateFix struct {
	LedgerStateFix *LedgerStateFix `protobuf:"bytes,903,opt,name=ledger_state_fix,json=ledgerStateFix,proto3,oneof"`
}

func (*Transaction_Payment) isTransaction_TxDetails() {}

func (*Transaction_OfferCreate) isTransaction_TxDetails() {}

func (*Transaction_OfferCancel) isTransaction_TxDetails() {}

func (*Transaction_TrustSet) isTransaction_TxDetails() {}

func (*Transaction_AccountSet) isTransaction_TxDetails() {}

func (*Transaction_AccountDelete) isTransaction_TxDetails() {}

func (*Transaction_SetRegularKey) isTransaction_TxDetails() {}

func (*Transaction_SignerListSet) isTransaction_TxDetails() {}

func (*Transaction_EscrowCreate) isTransaction_TxDetails() {}

func (*Transaction_EscrowFinish) isTransaction_TxDetails() {}

func (*Transaction_EscrowCancel) isTransaction_TxDetails() {}

func (*Transaction_PaymentChannelCreate) isTransaction_TxDetails() {}

func (*Transaction_PaymentChannelFund) isTransaction_TxDetails() {}

func (*Transaction_PaymentChannelClaim) isTransaction_TxDetails() {}

func (*Transaction_CheckCreate) isTransaction_TxDetails() {}

func (*Transaction_CheckCash) isTransaction_TxDetails() {}

func (*Transaction_CheckCancel) isTransaction_TxDetails() {}

func (*Transaction_DepositPreauth) isTransaction_TxDetails() {}

func (*Transaction_TicketCreate) isTransaction_TxDetails() {}

func (*Transaction_NftokenMint) isTransaction_TxDetails() {}

func (*Transaction_NftokenBurn) isTransaction_TxDetails() {}

func (*Transaction_NftokenCreateOffer) isTransaction_TxDetails() {}

func (*Transaction_NftokenCancelOffer) isTransaction_TxDetails() {}

func (*Transaction_NftokenAcceptOffer) isTransaction_TxDetails() {}

func (*Transaction_NftokenModify) isTransaction_TxDetails() {}

func (*Transaction_Clawback) isTransaction_TxDetails() {}

func (*Transaction_AmmCreate) isTransaction_TxDetails() {}

func (*Transaction_AmmDeposit) isTransaction_TxDetails() {}

func (*Transaction_AmmWithdraw) isTransaction_TxDetails() {}

func (*Transaction_AmmVote) isTransaction_TxDetails() {}

func (*Transaction_AmmBid) isTransaction_TxDetails() {}

func (*Transaction_AmmDelete) isTransaction_TxDetails() {}

func (*Transaction_AmmClawback) isTransaction_TxDetails() {}

func (*Transaction_XchainCreateBridge) isTransaction_TxDetails() {}

func (*Transaction_XchainModifyBridge) isTransaction_TxDetails() {}

func (*Transaction_XchainCreateClaimId) isTransaction_TxDetails() {}

func (*Transaction_XchainCommit) isTransaction_TxDetails() {}

func (*Transaction_XchainClaim) isTransaction_TxDetails() {}

func (*Transaction_XchainAccountCreateCommit) isTransaction_TxDetails() {}

func (*Transaction_XchainAddClaimAttestation) isTransaction_TxDetails() {}

func (*Transaction_XchainAddAccountCreateAttestation) isTransaction_TxDetails() {}

func (*Transaction_DidSet) isTransaction_TxDetails() {}

func (*Transaction_DidDelete) isTransaction_TxDetails() {}

func (*Transaction_OracleSet) isTransaction_TxDetails() {}

func (*Transaction_OracleDelete) isTransaction_TxDetails() {}

func (*Transaction_MptokenIssuanceCreate) isTransaction_TxDetails() {}

func (*Transaction_MptokenIssuanceDestroy) isTransaction_TxDetails() {}

func (*Transaction_MptokenIssuanceSet) isTransaction_TxDetails() {}

func (*Transaction_MptokenAuthorize) isTransaction_TxDetails() {}

func (*Transaction_CredentialCreate) isTransaction_TxDetails() {}

func (*Transaction_CredentialAccept) isTransaction_TxDetails() {}

func (*Transaction_CredentialDelete) isTransaction_TxDetails() {}

func (*Transaction_PermissionedDomainSet) isTransaction_TxDetails() {}

func (*Transaction_PermissionedDomainDelete) isTransaction_TxDetails() {}

func (*Transaction_DelegateSet) isTransaction_TxDetails() {}

func (*Transaction_Batch) isTransaction_TxDetails() {}

func (*Transaction_EnableAmendment) isTransaction_TxDetails() {}

func (*Transaction_SetFee) isTransaction_TxDetails() {}

func (*Transaction_UnlModify) isTransaction_TxDetails() {}

func (*Transaction_LedgerStateFix) isTransaction_TxDetails() {}

// Memo attached to a transaction
type Memo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary hex value, conventionally containing the content of the memo
	MemoData string `protobuf:"bytes,1,opt,name=memo_data,json=memoData,proto3" json:"memo_data,omitempty"`
	// Hex value representing characters allowed in URLs
	// Conventionally containing information on how the memo is encoded
	MemoFormat string `protobuf:"bytes,2,opt,name=memo_format,json=memoFormat,proto3" json:"memo_format,omitempty"`
	// Hex value representing characters allowed in URLs
	// Conventionally, a unique relation that defines the format of this memo
	MemoType      string `protobuf:"bytes,3,opt,name=memo_type,json=memoType,proto3" json:"memo_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_block_proto_rawDescGZIP(), []int{3}
}

func (x *Memo) GetMemoData() string {
	if x != nil {
		return x.MemoData
	}
	return ""
}

func (x *Memo) GetMemoFormat() string {
	if x != nil {
		return x.MemoFormat
	}
	return ""
}

func (x *Memo) GetMemoType() string {
	if x != nil {
		return x.MemoType
	}
	return ""
}

var File_sf_xrpl_type_v1_block_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x1bsf/xrpl/type/v1/block.proto\x12\x0fsf.xrpl.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1csf/xrpl/type/v1/signer.proto\x1a\x1dsf/xrpl/type/v1/payment.proto\x1a\x1bsf/xrpl/type/v1/offer.proto\x1a\x1fsf/xrpl/type/v1/trustline.proto\x1a\x1dsf/xrpl/type/v1/account.proto\x1a\x1csf/xrpl/type/v1/escrow.proto\x1a\x19sf/xrpl/type/v1/nft.proto\x1a%sf/xrpl/type/v1/payment_channel.proto\x1a\x1bsf/xrpl/type/v1/check.proto\x1a%sf/xrpl/type/v1/deposit_preauth.proto\x1a\x1csf/xrpl/type/v1/ticket.proto\x1a\x1esf/xrpl/type/v1/clawback.proto\x1a\x19sf/xrpl/type/v1/amm.proto\x1a\x1csf/xrpl/type/v1/xchain.proto\x1a\x19sf/xrpl/type/v1/did.proto\x1a\x1csf/xrpl/type/v1/oracle.proto\x1a\x1dsf/xrpl/type/v1/mptoken.proto\x1a sf/xrpl/type/v1/credential.proto\x1a)sf/xrpl/type/v1/permissioned_domain.proto\x1a\x1esf/xrpl/type/v1/delegate.proto\x1a\x1csf/xrpl/type/v1/system.proto\x1a\x1bsf/xrpl/type/v1/batch.proto\"\xfb\x01\n" +
	"\x05Block\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12/\n" +
	"\x06header\x18\x03 \x01(\v2\x17.sf.xrpl.type.v1.HeaderR\x06header\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12@\n" +
	"\ftransactions\x18\x05 \x03(\v2\x1c.sf.xrpl.type.v1.TransactionR\ftransactions\x129\n" +
	"\n" +
	"close_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\"\xed\x01\n" +
	"\x06Header\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12\x1f\n" +
	"\vtotal_drops\x18\x02 \x01(\x03R\n" +
	"totalDrops\x12!\n" +
	"\faccount_hash\x18\x03 \x01(\fR\vaccountHash\x12)\n" +
	"\x10transaction_hash\x18\x04 \x01(\fR\x0ftransactionHash\x122\n" +
	"\x15close_time_resolution\x18\x05 \x01(\rR\x13closeTimeResolution\x12\x1f\n" +
	"\vclose_flags\x18\x06 \x01(\rR\n" +
	"closeFlags\"\xce(\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12\x17\n" +
	"\atx_blob\x18\x04 \x01(\fR\x06txBlob\x12\x1b\n" +
	"\tmeta_blob\x18\x05 \x01(\fR\bmetaBlob\x12\x17\n" +
	"\atx_type\x18\x06 \x01(\tR\x06txType\x12\x18\n" +
	"\aaccount\x18\a \x01(\tR\aaccount\x12\x10\n" +
	"\x03fee\x18\b \x01(\x04R\x03fee\x12\x1a\n" +
	"\bsequence\x18\t \x01(\rR\bsequence\x12$\n" +
	"\x0eaccount_txn_id\x18\n" +
	" \x01(\tR\faccountTxnId\x12\x1a\n" +
	"\bdelegate\x18\v \x01(\tR\bdelegate\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\x120\n" +
	"\x14last_ledger_sequence\x18\r \x01(\rR\x12lastLedgerSequence\x12+\n" +
	"\x05memos\x18\x0e \x03(\v2\x15.sf.xrpl.type.v1.MemoR\x05memos\x12\x1d\n" +
	"\n" +
	"network_id\x18\x0f \x01(\rR\tnetworkId\x121\n" +
	"\asigners\x18\x10 \x03(\v2\x17.sf.xrpl.type.v1.SignerR\asigners\x12\x1d\n" +
	"\n" +
	"source_tag\x18\x11 \x01(\rR\tsourceTag\x12&\n" +
	"\x0fsigning_pub_key\x18\x12 \x01(\tR\rsigningPubKey\x12'\n" +
	"\x0fticket_sequence\x18\x13 \x01(\rR\x0eticketSequence\x12#\n" +
	"\rtxn_signature\x18\x14 \x01(\tR\ftxnSignature\x124\n" +
	"\apayment\x18\x1e \x01(\v2\x18.sf.xrpl.type.v1.PaymentH\x00R\apayment\x12A\n" +
	"\foffer_create\x18\x1f \x01(\v2\x1c.sf.xrpl.type.v1.OfferCreateH\x00R\vofferCreate\x12A\n" +
	"\foffer_cancel\x18  \x01(\v2\x1c.sf.xrpl.type.v1.OfferCancelH\x00R\vofferCancel\x128\n" +
	"\ttrust_set\x18! \x01(\v2\x19.sf.xrpl.type.v1.TrustSetH\x00R\btrustSet\x12>\n" +
	"\vaccount_set\x18\" \x01(\v2\x1b.sf.xrpl.type.v1.AccountSetH\x00R\n" +
	"accountSet\x12G\n" +
	"\x0eaccount_delete\x18# \x01(\v2\x1e.sf.xrpl.type.v1.AccountDeleteH\x00R\raccountDelete\x12H\n" +
	"\x0fset_regular_key\x18$ \x01(\v2\x1e.sf.xrpl.type.v1.SetRegularKeyH\x00R\rsetRegularKey\x12H\n" +
	"\x0fsigner_list_set\x18% \x01(\v2\x1e.sf.xrpl.type.v1.SignerListSetH\x00R\rsignerListSet\x12D\n" +
	"\rescrow_create\x18( \x01(\v2\x1d.sf.xrpl.type.v1.EscrowCreateH\x00R\fescrowCreate\x12D\n" +
	"\rescrow_finish\x18) \x01(\v2\x1d.sf.xrpl.type.v1.EscrowFinishH\x00R\fescrowFinish\x12D\n" +
	"\rescrow_cancel\x18* \x01(\v2\x1d.sf.xrpl.type.v1.EscrowCancelH\x00R\fescrowCancel\x12]\n" +
	"\x16payment_channel_create\x18+ \x01(\v2%.sf.xrpl.type.v1.PaymentChannelCreateH\x00R\x14paymentChannelCreate\x12W\n" +
	"\x14payment_channel_fund\x18, \x01(\v2#.sf.xrpl.type.v1.PaymentChannelFundH\x00R\x12paymentChannelFund\x12Z\n" +
	"\x15payment_channel_claim\x18- \x01(\v2$.sf.xrpl.type.v1.PaymentChannelClaimH\x00R\x13paymentChannelClaim\x12A\n" +
	"\fcheck_create\x18. \x01(\v2\x1c.sf.xrpl.type.v1.CheckCreateH\x00R\vcheckCreate\x12;\n" +
	"\n" +
	"check_cash\x18/ \x01(\v2\x1a.sf.xrpl.type.v1.CheckCashH\x00R\tcheckCash\x12A\n" +
	"\fcheck_cancel\x180 \x01(\v2\x1c.sf.xrpl.type.v1.CheckCancelH\x00R\vcheckCancel\x12J\n" +
	"\x0fdeposit_preauth\x181 \x01(\v2\x1f.sf.xrpl.type.v1.DepositPreauthH\x00R\x0edepositPreauth\x12D\n" +
	"\rticket_create\x182 \x01(\v2\x1d.sf.xrpl.type.v1.TicketCreateH\x00R\fticketCreate\x12A\n" +
	"\fnftoken_mint\x18< \x01(\v2\x1c.sf.xrpl.type.v1.NFTokenMintH\x00R\vnftokenMint\x12A\n" +
	"\fnftoken_burn\x18= \x01(\v2\x1c.sf.xrpl.type.v1.NFTokenBurnH\x00R\vnftokenBurn\x12W\n" +
	"\x14nftoken_create_offer\x18> \x01(\v2#.sf.xrpl.type.v1.NFTokenCreateOfferH\x00R\x12nftokenCreateOffer\x12W\n" +
	"\x14nftoken_cancel_offer\x18? \x01(\v2#.sf.xrpl.type.v1.NFTokenCancelOfferH\x00R\x12nftokenCancelOffer\x12W\n" +
	"\x14nftoken_accept_offer\x18@ \x01(\v2#.sf.xrpl.type.v1.NFTokenAcceptOfferH\x00R\x12nftokenAcceptOffer\x12G\n" +
	"\x0enftoken_modify\x18A \x01(\v2\x1e.sf.xrpl.type.v1.NFTokenModifyH\x00R\rnftokenModify\x127\n" +
	"\bclawback\x18F \x01(\v2\x19.sf.xrpl.type.v1.ClawbackH\x00R\bclawback\x12;\n" +
	"\n" +
	"amm_create\x18P \x01(\v2\x1a.sf.xrpl.type.v1.AMMCreateH\x00R\tammCreate\x12>\n" +
	"\vamm_deposit\x18Q \x01(\v2\x1b.sf.xrpl.type.v1.AMMDepositH\x00R\n" +
	"ammDeposit\x12A\n" +
	"\famm_withdraw\x18R \x01(\v2\x1c.sf.xrpl.type.v1.AMMWithdrawH\x00R\vammWithdraw\x125\n" +
	"\bamm_vote\x18S \x01(\v2\x18.sf.xrpl.type.v1.AMMVoteH\x00R\aammVote\x122\n" +
	"\aamm_bid\x18T \x01(\v2\x17.sf.xrpl.type.v1.AMMBidH\x00R\x06ammBid\x12;\n" +
	"\n" +
	"amm_delete\x18U \x01(\v2\x1a.sf.xrpl.type.v1.AMMDeleteH\x00R\tammDelete\x12A\n" +
	"\famm_clawback\x18V \x01(\v2\x1c.sf.xrpl.type.v1.AMMClawbackH\x00R\vammClawback\x12W\n" +
	"\x14xchain_create_bridge\x18Z \x01(\v2#.sf.xrpl.type.v1.XChainCreateBridgeH\x00R\x12xchainCreateBridge\x12W\n" +
	"\x14xchain_modify_bridge\x18[ \x01(\v2#.sf.xrpl.type.v1.XChainModifyBridgeH\x00R\x12xchainModifyBridge\x12[\n" +
	"\x16xchain_create_claim_id\x18\\ \x01(\v2$.sf.xrpl.type.v1.XChainCreateClaimIDH\x00R\x13xchainCreateClaimId\x12D\n" +
	"\rxchain_commit\x18] \x01(\v2\x1d.sf.xrpl.type.v1.XChainCommitH\x00R\fxchainCommit\x12A\n" +
	"\fxchain_claim\x18^ \x01(\v2\x1c.sf.xrpl.type.v1.XChainClaimH\x00R\vxchainClaim\x12m\n" +
	"\x1cxchain_account_create_commit\x18_ \x01(\v2*.sf.xrpl.type.v1.XChainAccountCreateCommitH\x00R\x19xchainAccountCreateCommit\x12m\n" +
	"\x1cxchain_add_claim_attestation\x18` \x01(\v2*.sf.xrpl.type.v1.XChainAddClaimAttestationH\x00R\x19xchainAddClaimAttestation\x12\x86\x01\n" +
	"%xchain_add_account_create_attestation\x18a \x01(\v22.sf.xrpl.type.v1.XChainAddAccountCreateAttestationH\x00R!xchainAddAccountCreateAttestation\x122\n" +
	"\adid_set\x18d \x01(\v2\x17.sf.xrpl.type.v1.DIDSetH\x00R\x06didSet\x12;\n" +
	"\n" +
	"did_delete\x18e \x01(\v2\x1a.sf.xrpl.type.v1.DIDDeleteH\x00R\tdidDelete\x12;\n" +
	"\n" +
	"oracle_set\x18f \x01(\v2\x1a.sf.xrpl.type.v1.OracleSetH\x00R\toracleSet\x12D\n" +
	"\roracle_delete\x18g \x01(\v2\x1d.sf.xrpl.type.v1.OracleDeleteH\x00R\foracleDelete\x12`\n" +
	"\x17mptoken_issuance_create\x18n \x01(\v2&.sf.xrpl.type.v1.MPTokenIssuanceCreateH\x00R\x15mptokenIssuanceCreate\x12c\n" +
	"\x18mptoken_issuance_destroy\x18o \x01(\v2'.sf.xrpl.type.v1.MPTokenIssuanceDestroyH\x00R\x16mptokenIssuanceDestroy\x12W\n" +
	"\x14mptoken_issuance_set\x18p \x01(\v2#.sf.xrpl.type.v1.MPTokenIssuanceSetH\x00R\x12mptokenIssuanceSet\x12P\n" +
	"\x11mptoken_authorize\x18q \x01(\v2!.sf.xrpl.type.v1.MPTokenAuthorizeH\x00R\x10mptokenAuthorize\x12P\n" +
	"\x11credential_create\x18x \x01(\v2!.sf.xrpl.type.v1.CredentialCreateH\x00R\x10credentialCreate\x12P\n" +
	"\x11credential_accept\x18y \x01(\v2!.sf.xrpl.type.v1.CredentialAcceptH\x00R\x10credentialAccept\x12P\n" +
	"\x11credential_delete\x18z \x01(\v2!.sf.xrpl.type.v1.CredentialDeleteH\x00R\x10credentialDelete\x12a\n" +
	"\x17permissioned_domain_set\x18\x82\x01 \x01(\v2&.sf.xrpl.type.v1.PermissionedDomainSetH\x00R\x15permissionedDomainSet\x12j\n" +
	"\x1apermissioned_domain_delete\x18\x83\x01 \x01(\v2).sf.xrpl.type.v1.PermissionedDomainDeleteH\x00R\x18permissionedDomainDelete\x12B\n" +
	"\fdelegate_set\x18\x84\x01 \x01(\v2\x1c.sf.xrpl.type.v1.DelegateSetH\x00R\vdelegateSet\x12/\n" +
	"\x05batch\x18\x85\x01 \x01(\v2\x16.sf.xrpl.type.v1.BatchH\x00R\x05batch\x12N\n" +
	"\x10enable_amendment\x18\x84\a \x01(\v2 .sf.xrpl.type.v1.EnableAmendmentH\x00R\x0fenableAmendment\x123\n" +
	"\aset_fee\x18\x85\a \x01(\v2\x17.sf.xrpl.type.v1.SetFeeH\x00R\x06setFee\x12<\n" +
	"\n" +
	"unl_modify\x18\x86\a \x01(\v2\x1a.sf.xrpl.type.v1.UNLModifyH\x00R\tunlModify\x12L\n" +
	"\x10ledger_state_fix\x18\x87\a \x01(\v2\x1f.sf.xrpl.type.v1.LedgerStateFixH\x00R\x0eledgerStateFixB\f\n" +
	"\n" +
	"tx_details\"a\n" +
	"\x04Memo\x12\x1b\n" +
	"\tmemo_data\x18\x01 \x01(\tR\bmemoData\x12\x1f\n" +
	"\vmemo_format\x18\x02 \x01(\tR\n" +
	"memoFormat\x12\x1b\n" +
	"\tmemo_type\x18\x03 \x01(\tR\bmemoTypeBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_block_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_block_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_block_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_block_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_block_proto_rawDesc), len(file_sf_xrpl_type_v1_block_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_block_proto_rawDescData
}

var file_sf_xrpl_type_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_xrpl_type_v1_block_proto_goTypes = []any{
	(*Block)(nil),                             // 0: sf.xrpl.type.v1.Block
	(*Header)(nil),                            // 1: sf.xrpl.type.v1.Header
	(*Transaction)(nil),                       // 2: sf.xrpl.type.v1.Transaction
	(*Memo)(nil),                              // 3: sf.xrpl.type.v1.Memo
	(*timestamppb.Timestamp)(nil),             // 4: google.protobuf.Timestamp
	(*Signer)(nil),                            // 5: sf.xrpl.type.v1.Signer
	(*Payment)(nil),                           // 6: sf.xrpl.type.v1.Payment
	(*OfferCreate)(nil),                       // 7: sf.xrpl.type.v1.OfferCreate
	(*OfferCancel)(nil),                       // 8: sf.xrpl.type.v1.OfferCancel
	(*TrustSet)(nil),                          // 9: sf.xrpl.type.v1.TrustSet
	(*AccountSet)(nil),                        // 10: sf.xrpl.type.v1.AccountSet
	(*AccountDelete)(nil),                     // 11: sf.xrpl.type.v1.AccountDelete
	(*SetRegularKey)(nil),                     // 12: sf.xrpl.type.v1.SetRegularKey
	(*SignerListSet)(nil),                     // 13: sf.xrpl.type.v1.SignerListSet
	(*EscrowCreate)(nil),                      // 14: sf.xrpl.type.v1.EscrowCreate
	(*EscrowFinish)(nil),                      // 15: sf.xrpl.type.v1.EscrowFinish
	(*EscrowCancel)(nil),                      // 16: sf.xrpl.type.v1.EscrowCancel
	(*PaymentChannelCreate)(nil),              // 17: sf.xrpl.type.v1.PaymentChannelCreate
	(*PaymentChannelFund)(nil),                // 18: sf.xrpl.type.v1.PaymentChannelFund
	(*PaymentChannelClaim)(nil),               // 19: sf.xrpl.type.v1.PaymentChannelClaim
	(*CheckCreate)(nil),                       // 20: sf.xrpl.type.v1.CheckCreate
	(*CheckCash)(nil),                         // 21: sf.xrpl.type.v1.CheckCash
	(*CheckCancel)(nil),                       // 22: sf.xrpl.type.v1.CheckCancel
	(*DepositPreauth)(nil),                    // 23: sf.xrpl.type.v1.DepositPreauth
	(*TicketCreate)(nil),                      // 24: sf.xrpl.type.v1.TicketCreate
	(*NFTokenMint)(nil),                       // 25: sf.xrpl.type.v1.NFTokenMint
	(*NFTokenBurn)(nil),                       // 26: sf.xrpl.type.v1.NFTokenBurn
	(*NFTokenCreateOffer)(nil),                // 27: sf.xrpl.type.v1.NFTokenCreateOffer
	(*NFTokenCancelOffer)(nil),                // 28: sf.xrpl.type.v1.NFTokenCancelOffer
	(*NFTokenAcceptOffer)(nil),                // 29: sf.xrpl.type.v1.NFTokenAcceptOffer
	(*NFTokenModify)(nil),                     // 30: sf.xrpl.type.v1.NFTokenModify
	(*Clawback)(nil),                          // 31: sf.xrpl.type.v1.Clawback
	(*AMMCreate)(nil),                         // 32: sf.xrpl.type.v1.AMMCreate
	(*AMMDeposit)(nil),                        // 33: sf.xrpl.type.v1.AMMDeposit
	(*AMMWithdraw)(nil),                       // 34: sf.xrpl.type.v1.AMMWithdraw
	(*AMMVote)(nil),                           // 35: sf.xrpl.type.v1.AMMVote
	(*AMMBid)(nil),                            // 36: sf.xrpl.type.v1.AMMBid
	(*AMMDelete)(nil),                         // 37: sf.xrpl.type.v1.AMMDelete
	(*AMMClawback)(nil),                       // 38: sf.xrpl.type.v1.AMMClawback
	(*XChainCreateBridge)(nil),                // 39: sf.xrpl.type.v1.XChainCreateBridge
	(*XChainModifyBridge)(nil),                // 40: sf.xrpl.type.v1.XChainModifyBridge
	(*XChainCreateClaimID)(nil),               // 41: sf.xrpl.type.v1.XChainCreateClaimID
	(*XChainCommit)(nil),                      // 42: sf.xrpl.type.v1.XChainCommit
	(*XChainClaim)(nil),                       // 43: sf.xrpl.type.v1.XChainClaim
	(*XChainAccountCreateCommit)(nil),         // 44: sf.xrpl.type.v1.XChainAccountCreateCommit
	(*XChainAddClaimAttestation)(nil),         // 45: sf.xrpl.type.v1.XChainAddClaimAttestation
	(*XChainAddAccountCreateAttestation)(nil), // 46: sf.xrpl.type.v1.XChainAddAccountCreateAttestation
	(*DIDSet)(nil),                            // 47: sf.xrpl.type.v1.DIDSet
	(*DIDDelete)(nil),                         // 48: sf.xrpl.type.v1.DIDDelete
	(*OracleSet)(nil),                         // 49: sf.xrpl.type.v1.OracleSet
	(*OracleDelete)(nil),                      // 50: sf.xrpl.type.v1.OracleDelete
	(*MPTokenIssuanceCreate)(nil),             // 51: sf.xrpl.type.v1.MPTokenIssuanceCreate
	(*MPTokenIssuanceDestroy)(nil),            // 52: sf.xrpl.type.v1.MPTokenIssuanceDestroy
	(*MPTokenIssuanceSet)(nil),                // 53: sf.xrpl.type.v1.MPTokenIssuanceSet
	(*MPTokenAuthorize)(nil),                  // 54: sf.xrpl.type.v1.MPTokenAuthorize
	(*CredentialCreate)(nil),                  // 55: sf.xrpl.type.v1.CredentialCreate
	(*CredentialAccept)(nil),                  // 56: sf.xrpl.type.v1.CredentialAccept
	(*CredentialDelete)(nil),                  // 57: sf.xrpl.type.v1.CredentialDelete
	(*PermissionedDomainSet)(nil),             // 58: sf.xrpl.type.v1.PermissionedDomainSet
	(*PermissionedDomainDelete)(nil),          // 59: sf.xrpl.type.v1.PermissionedDomainDelete
	(*DelegateSet)(nil),                       // 60: sf.xrpl.type.v1.DelegateSet
	(*Batch)(nil),                             // 61: sf.xrpl.type.v1.Batch
	(*EnableAmendment)(nil),                   // 62: sf.xrpl.type.v1.EnableAmendment
	(*SetFee)(nil),                            // 63: sf.xrpl.type.v1.SetFee
	(*UNLModify)(nil),                         // 64: sf.xrpl.type.v1.UNLModify
	(*LedgerStateFix)(nil),                    // 65: sf.xrpl.type.v1.LedgerStateFix
}
var file_sf_xrpl_type_v1_block_proto_depIdxs = []int32{
	1,  // 0: sf.xrpl.type.v1.Block.header:type_name -> sf.xrpl.type.v1.Header
	2,  // 1: sf.xrpl.type.v1.Block.transactions:type_name -> sf.xrpl.type.v1.Transaction
	4,  // 2: sf.xrpl.type.v1.Block.close_time:type_name -> google.protobuf.Timestamp
	3,  // 3: sf.xrpl.type.v1.Transaction.memos:type_name -> sf.xrpl.type.v1.Memo
	5,  // 4: sf.xrpl.type.v1.Transaction.signers:type_name -> sf.xrpl.type.v1.Signer
	6,  // 5: sf.xrpl.type.v1.Transaction.payment:type_name -> sf.xrpl.type.v1.Payment
	7,  // 6: sf.xrpl.type.v1.Transaction.offer_create:type_name -> sf.xrpl.type.v1.OfferCreate
	8,  // 7: sf.xrpl.type.v1.Transaction.offer_cancel:type_name -> sf.xrpl.type.v1.OfferCancel
	9,  // 8: sf.xrpl.type.v1.Transaction.trust_set:type_name -> sf.xrpl.type.v1.TrustSet
	10, // 9: sf.xrpl.type.v1.Transaction.account_set:type_name -> sf.xrpl.type.v1.AccountSet
	11, // 10: sf.xrpl.type.v1.Transaction.account_delete:type_name -> sf.xrpl.type.v1.AccountDelete
	12, // 11: sf.xrpl.type.v1.Transaction.set_regular_key:type_name -> sf.xrpl.type.v1.SetRegularKey
	13, // 12: sf.xrpl.type.v1.Transaction.signer_list_set:type_name -> sf.xrpl.type.v1.SignerListSet
	14, // 13: sf.xrpl.type.v1.Transaction.escrow_create:type_name -> sf.xrpl.type.v1.EscrowCreate
	15, // 14: sf.xrpl.type.v1.Transaction.escrow_finish:type_name -> sf.xrpl.type.v1.EscrowFinish
	16, // 15: sf.xrpl.type.v1.Transaction.escrow_cancel:type_name -> sf.xrpl.type.v1.EscrowCancel
	17, // 16: sf.xrpl.type.v1.Transaction.payment_channel_create:type_name -> sf.xrpl.type.v1.PaymentChannelCreate
	18, // 17: sf.xrpl.type.v1.Transaction.payment_channel_fund:type_name -> sf.xrpl.type.v1.PaymentChannelFund
	19, // 18: sf.xrpl.type.v1.Transaction.payment_channel_claim:type_name -> sf.xrpl.type.v1.PaymentChannelClaim
	20, // 19: sf.xrpl.type.v1.Transaction.check_create:type_name -> sf.xrpl.type.v1.CheckCreate
	21, // 20: sf.xrpl.type.v1.Transaction.check_cash:type_name -> sf.xrpl.type.v1.CheckCash
	22, // 21: sf.xrpl.type.v1.Transaction.check_cancel:type_name -> sf.xrpl.type.v1.CheckCancel
	23, // 22: sf.xrpl.type.v1.Transaction.deposit_preauth:type_name -> sf.xrpl.type.v1.DepositPreauth
	24, // 23: sf.xrpl.type.v1.Transaction.ticket_create:type_name -> sf.xrpl.type.v1.TicketCreate
	25, // 24: sf.xrpl.type.v1.Transaction.nftoken_mint:type_name -> sf.xrpl.type.v1.NFTokenMint
	26, // 25: sf.xrpl.type.v1.Transaction.nftoken_burn:type_name -> sf.xrpl.type.v1.NFTokenBurn
	27, // 26: sf.xrpl.type.v1.Transaction.nftoken_create_offer:type_name -> sf.xrpl.type.v1.NFTokenCreateOffer
	28, // 27: sf.xrpl.type.v1.Transaction.nftoken_cancel_offer:type_name -> sf.xrpl.type.v1.NFTokenCancelOffer
	29, // 28: sf.xrpl.type.v1.Transaction.nftoken_accept_offer:type_name -> sf.xrpl.type.v1.NFTokenAcceptOffer
	30, // 29: sf.xrpl.type.v1.Transaction.nftoken_modify:type_name -> sf.xrpl.type.v1.NFTokenModify
	31, // 30: sf.xrpl.type.v1.Transaction.clawback:type_name -> sf.xrpl.type.v1.Clawback
	32, // 31: sf.xrpl.type.v1.Transaction.amm_create:type_name -> sf.xrpl.type.v1.AMMCreate
	33, // 32: sf.xrpl.type.v1.Transaction.amm_deposit:type_name -> sf.xrpl.type.v1.AMMDeposit
	34, // 33: sf.xrpl.type.v1.Transaction.amm_withdraw:type_name -> sf.xrpl.type.v1.AMMWithdraw
	35, // 34: sf.xrpl.type.v1.Transaction.amm_vote:type_name -> sf.xrpl.type.v1.AMMVote
	36, // 35: sf.xrpl.type.v1.Transaction.amm_bid:type_name -> sf.xrpl.type.v1.AMMBid
	37, // 36: sf.xrpl.type.v1.Transaction.amm_delete:type_name -> sf.xrpl.type.v1.AMMDelete
	38, // 37: sf.xrpl.type.v1.Transaction.amm_clawback:type_name -> sf.xrpl.type.v1.AMMClawback
	39, // 38: sf.xrpl.type.v1.Transaction.xchain_create_bridge:type_name -> sf.xrpl.type.v1.XChainCreateBridge
	40, // 39: sf.xrpl.type.v1.Transaction.xchain_modify_bridge:type_name -> sf.xrpl.type.v1.XChainModifyBridge
	41, // 40: sf.xrpl.type.v1.Transaction.xchain_create_claim_id:type_name -> sf.xrpl.type.v1.XChainCreateClaimID
	42, // 41: sf.xrpl.type.v1.Transaction.xchain_commit:type_name -> sf.xrpl.type.v1.XChainCommit
	43, // 42: sf.xrpl.type.v1.Transaction.xchain_claim:type_name -> sf.xrpl.type.v1.XChainClaim
	44, // 43: sf.xrpl.type.v1.Transaction.xchain_account_create_commit:type_name -> sf.xrpl.type.v1.XChainAccountCreateCommit
	45, // 44: sf.xrpl.type.v1.Transaction.xchain_add_claim_attestation:type_name -> sf.xrpl.type.v1.XChainAddClaimAttestation
	46, // 45: sf.xrpl.type.v1.Transaction.xchain_add_account_create_attestation:type_name -> sf.xrpl.type.v1.XChainAddAccountCreateAttestation
	47, // 46: sf.xrpl.type.v1.Transaction.did_set:type_name -> sf.xrpl.type.v1.DIDSet
	48, // 47: sf.xrpl.type.v1.Transaction.did_delete:type_name -> sf.xrpl.type.v1.DIDDelete
	49, // 48: sf.xrpl.type.v1.Transaction.oracle_set:type_name -> sf.xrpl.type.v1.OracleSet
	50, // 49: sf.xrpl.type.v1.Transaction.oracle_delete:type_name -> sf.xrpl.type.v1.OracleDelete
	51, // 50: sf.xrpl.type.v1.Transaction.mptoken_issuance_create:type_name -> sf.xrpl.type.v1.MPTokenIssuanceCreate
	52, // 51: sf.xrpl.type.v1.Transaction.mptoken_issuance_destroy:type_name -> sf.xrpl.type.v1.MPTokenIssuanceDestroy
	53, // 52: sf.xrpl.type.v1.Transaction.mptoken_issuance_set:type_name -> sf.xrpl.type.v1.MPTokenIssuanceSet
	54, // 53: sf.xrpl.type.v1.Transaction.mptoken_authorize:type_name -> sf.xrpl.type.v1.MPTokenAuthorize
	55, // 54: sf.xrpl.type.v1.Transaction.credential_create:type_name -> sf.xrpl.type.v1.CredentialCreate
	56, // 55: sf.xrpl.type.v1.Transaction.credential_accept:type_name -> sf.xrpl.type.v1.CredentialAccept
	57, // 56: sf.xrpl.type.v1.Transaction.credential_delete:type_name -> sf.xrpl.type.v1.CredentialDelete
	58, // 57: sf.xrpl.type.v1.Transaction.permissioned_domain_set:type_name -> sf.xrpl.type.v1.PermissionedDomainSet
	59, // 58: sf.xrpl.type.v1.Transaction.permissioned_domain_delete:type_name -> sf.xrpl.type.v1.PermissionedDomainDelete
	60, // 59: sf.xrpl.type.v1.Transaction.delegate_set:type_name -> sf.xrpl.type.v1.DelegateSet
	61, // 60: sf.xrpl.type.v1.Transaction.batch:type_name -> sf.xrpl.type.v1.Batch
	62, // 61: sf.xrpl.type.v1.Transaction.enable_amendment:type_name -> sf.xrpl.type.v1.EnableAmendment
	63, // 62: sf.xrpl.type.v1.Transaction.set_fee:type_name -> sf.xrpl.type.v1.SetFee
	64, // 63: sf.xrpl.type.v1.Transaction.unl_modify:type_name -> sf.xrpl.type.v1.UNLModify
	65, // 64: sf.xrpl.type.v1.Transaction.ledger_state_fix:type_name -> sf.xrpl.type.v1.LedgerStateFix
	65, // [65:65] is the sub-list for method output_type
	65, // [65:65] is the sub-list for method input_type
	65, // [65:65] is the sub-list for extension type_name
	65, // [65:65] is the sub-list for extension extendee
	0,  // [0:65] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_block_proto_init() }
func file_sf_xrpl_type_v1_block_proto_init() {
	if File_sf_xrpl_type_v1_block_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_signer_proto_init()
	file_sf_xrpl_type_v1_payment_proto_init()
	file_sf_xrpl_type_v1_offer_proto_init()
	file_sf_xrpl_type_v1_trustline_proto_init()
	file_sf_xrpl_type_v1_account_proto_init()
	file_sf_xrpl_type_v1_escrow_proto_init()
	file_sf_xrpl_type_v1_nft_proto_init()
	file_sf_xrpl_type_v1_payment_channel_proto_init()
	file_sf_xrpl_type_v1_check_proto_init()
	file_sf_xrpl_type_v1_deposit_preauth_proto_init()
	file_sf_xrpl_type_v1_ticket_proto_init()
	file_sf_xrpl_type_v1_clawback_proto_init()
	file_sf_xrpl_type_v1_amm_proto_init()
	file_sf_xrpl_type_v1_xchain_proto_init()
	file_sf_xrpl_type_v1_did_proto_init()
	file_sf_xrpl_type_v1_oracle_proto_init()
	file_sf_xrpl_type_v1_mptoken_proto_init()
	file_sf_xrpl_type_v1_credential_proto_init()
	file_sf_xrpl_type_v1_permissioned_domain_proto_init()
	file_sf_xrpl_type_v1_delegate_proto_init()
	file_sf_xrpl_type_v1_system_proto_init()
	file_sf_xrpl_type_v1_batch_proto_init()
	file_sf_xrpl_type_v1_block_proto_msgTypes[2].OneofWrappers = []any{
		(*Transaction_Payment)(nil),
		(*Transaction_OfferCreate)(nil),
		(*Transaction_OfferCancel)(nil),
		(*Transaction_TrustSet)(nil),
		(*Transaction_AccountSet)(nil),
		(*Transaction_AccountDelete)(nil),
		(*Transaction_SetRegularKey)(nil),
		(*Transaction_SignerListSet)(nil),
		(*Transaction_EscrowCreate)(nil),
		(*Transaction_EscrowFinish)(nil),
		(*Transaction_EscrowCancel)(nil),
		(*Transaction_PaymentChannelCreate)(nil),
		(*Transaction_PaymentChannelFund)(nil),
		(*Transaction_PaymentChannelClaim)(nil),
		(*Transaction_CheckCreate)(nil),
		(*Transaction_CheckCash)(nil),
		(*Transaction_CheckCancel)(nil),
		(*Transaction_DepositPreauth)(nil),
		(*Transaction_TicketCreate)(nil),
		(*Transaction_NftokenMint)(nil),
		(*Transaction_NftokenBurn)(nil),
		(*Transaction_NftokenCreateOffer)(nil),
		(*Transaction_NftokenCancelOffer)(nil),
		(*Transaction_NftokenAcceptOffer)(nil),
		(*Transaction_NftokenModify)(nil),
		(*Transaction_Clawback)(nil),
		(*Transaction_AmmCreate)(nil),
		(*Transaction_AmmDeposit)(nil),
		(*Transaction_AmmWithdraw)(nil),
		(*Transaction_AmmVote)(nil),
		(*Transaction_AmmBid)(nil),
		(*Transaction_AmmDelete)(nil),
		(*Transaction_AmmClawback)(nil),
		(*Transaction_XchainCreateBridge)(nil),
		(*Transaction_XchainModifyBridge)(nil),
		(*Transaction_XchainCreateClaimId)(nil),
		(*Transaction_XchainCommit)(nil),
		(*Transaction_XchainClaim)(nil),
		(*Transaction_XchainAccountCreateCommit)(nil),
		(*Transaction_XchainAddClaimAttestation)(nil),
		(*Transaction_XchainAddAccountCreateAttestation)(nil),
		(*Transaction_DidSet)(nil),
		(*Transaction_DidDelete)(nil),
		(*Transaction_OracleSet)(nil),
		(*Transaction_OracleDelete)(nil),
		(*Transaction_MptokenIssuanceCreate)(nil),
		(*Transaction_MptokenIssuanceDestroy)(nil),
		(*Transaction_MptokenIssuanceSet)(nil),
		(*Transaction_MptokenAuthorize)(nil),
		(*Transaction_CredentialCreate)(nil),
		(*Transaction_CredentialAccept)(nil),
		(*Transaction_CredentialDelete)(nil),
		(*Transaction_PermissionedDomainSet)(nil),
		(*Transaction_PermissionedDomainDelete)(nil),
		(*Transaction_DelegateSet)(nil),
		(*Transaction_Batch)(nil),
		(*Transaction_EnableAmendment)(nil),
		(*Transaction_SetFee)(nil),
		(*Transaction_UnlModify)(nil),
		(*Transaction_LedgerStateFix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_block_proto_rawDesc), len(file_sf_xrpl_type_v1_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_block_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_block_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_block_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_block_proto = out.File
	file_sf_xrpl_type_v1_block_proto_goTypes = nil
	file_sf_xrpl_type_v1_block_proto_depIdxs = nil
}
