// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/clawback.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Clawback - Claws back issued tokens from a holder
// Reference: https://xrpl.org/clawback.html
type Clawback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount to claw back (includes holder's address in issuer field)
	Amount *Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// (Optional) Holder account for MPT clawback
	Holder        string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clawback) Reset() {
	*x = Clawback{}
	mi := &file_sf_xrpl_type_v1_clawback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clawback) ProtoMessage() {}

func (x *Clawback) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_clawback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clawback.ProtoReflect.Descriptor instead.
func (*Clawback) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_clawback_proto_rawDescGZIP(), []int{0}
}

func (x *Clawback) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Clawback) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

var File_sf_xrpl_type_v1_clawback_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_clawback_proto_rawDesc = "" +
	"\n" +
	"\x1esf/xrpl/type/v1/clawback.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"S\n" +
	"\bClawback\x12/\n" +
	"\x06amount\x18\x01 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holderBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_clawback_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_clawback_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_clawback_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_clawback_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_clawback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_clawback_proto_rawDesc), len(file_sf_xrpl_type_v1_clawback_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_clawback_proto_rawDescData
}

var file_sf_xrpl_type_v1_clawback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sf_xrpl_type_v1_clawback_proto_goTypes = []any{
	(*Clawback)(nil), // 0: sf.xrpl.type.v1.Clawback
	(*Amount)(nil),   // 1: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_clawback_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.Clawback.amount:type_name -> sf.xrpl.type.v1.Amount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_clawback_proto_init() }
func file_sf_xrpl_type_v1_clawback_proto_init() {
	if File_sf_xrpl_type_v1_clawback_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_clawback_proto_rawDesc), len(file_sf_xrpl_type_v1_clawback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_clawback_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_clawback_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_clawback_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_clawback_proto = out.File
	file_sf_xrpl_type_v1_clawback_proto_goTypes = nil
	file_sf_xrpl_type_v1_clawback_proto_depIdxs = nil
}
