// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/contract.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractCreate - Creates a smart contract
// Reference: https://xrpl.org/contractcreate.html
type ContractCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Contract bytecode (hex)
	ContractCode string `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	// (Optional) Hash of contract bytecode
	ContractHash string `protobuf:"bytes,2,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	// (Optional) Function definitions
	Functions []*ContractFunction `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	// (Optional) Instance parameter definitions
	InstanceParameters []string `protobuf:"bytes,4,rep,name=instance_parameters,json=instanceParameters,proto3" json:"instance_parameters,omitempty"`
	// (Optional) Instance parameter values
	InstanceParameterValues []string `protobuf:"bytes,5,rep,name=instance_parameter_values,json=instanceParameterValues,proto3" json:"instance_parameter_values,omitempty"`
	// (Optional) URI for contract metadata
	Uri           string `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractCreate) Reset() {
	*x = ContractCreate{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCreate) ProtoMessage() {}

func (x *ContractCreate) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCreate.ProtoReflect.Descriptor instead.
func (*ContractCreate) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractCreate) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *ContractCreate) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *ContractCreate) GetFunctions() []*ContractFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ContractCreate) GetInstanceParameters() []string {
	if x != nil {
		return x.InstanceParameters
	}
	return nil
}

func (x *ContractCreate) GetInstanceParameterValues() []string {
	if x != nil {
		return x.InstanceParameterValues
	}
	return nil
}

func (x *ContractCreate) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ContractFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    []string               `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractFunction) Reset() {
	*x = ContractFunction{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFunction) ProtoMessage() {}

func (x *ContractFunction) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFunction.ProtoReflect.Descriptor instead.
func (*ContractFunction) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractFunction) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ContractModify - Modifies a smart contract
// Reference: https://xrpl.org/contractmodify.html
type ContractModify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Contract account to modify
	ContractAccount string `protobuf:"bytes,1,opt,name=contract_account,json=contractAccount,proto3" json:"contract_account,omitempty"`
	// (Optional) New owner
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// (Optional) New contract bytecode (hex)
	ContractCode string `protobuf:"bytes,3,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	// (Optional) New contract hash
	ContractHash string `protobuf:"bytes,4,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	// (Optional) Updated function definitions
	Functions []*ContractFunction `protobuf:"bytes,5,rep,name=functions,proto3" json:"functions,omitempty"`
	// (Optional) Updated instance parameters
	InstanceParameters []string `protobuf:"bytes,6,rep,name=instance_parameters,json=instanceParameters,proto3" json:"instance_parameters,omitempty"`
	// (Optional) Updated instance parameter values
	InstanceParameterValues []string `protobuf:"bytes,7,rep,name=instance_parameter_values,json=instanceParameterValues,proto3" json:"instance_parameter_values,omitempty"`
	// (Optional) Updated URI
	Uri           string `protobuf:"bytes,8,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractModify) Reset() {
	*x = ContractModify{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractModify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractModify) ProtoMessage() {}

func (x *ContractModify) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractModify.ProtoReflect.Descriptor instead.
func (*ContractModify) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ContractModify) GetContractAccount() string {
	if x != nil {
		return x.ContractAccount
	}
	return ""
}

func (x *ContractModify) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ContractModify) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *ContractModify) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *ContractModify) GetFunctions() []*ContractFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ContractModify) GetInstanceParameters() []string {
	if x != nil {
		return x.InstanceParameters
	}
	return nil
}

func (x *ContractModify) GetInstanceParameterValues() []string {
	if x != nil {
		return x.InstanceParameterValues
	}
	return nil
}

func (x *ContractModify) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// ContractDelete - Deletes a smart contract
// Reference: https://xrpl.org/contractdelete.html
type ContractDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract account to delete
	ContractAccount string `protobuf:"bytes,1,opt,name=contract_account,json=contractAccount,proto3" json:"contract_account,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractDelete) Reset() {
	*x = ContractDelete{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDelete) ProtoMessage() {}

func (x *ContractDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDelete.ProtoReflect.Descriptor instead.
func (*ContractDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ContractDelete) GetContractAccount() string {
	if x != nil {
		return x.ContractAccount
	}
	return ""
}

// ContractClawback - Claws back funds from a contract
// Reference: https://xrpl.org/contractclawback.html
type ContractClawback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Contract account
	ContractAccount string `protobuf:"bytes,1,opt,name=contract_account,json=contractAccount,proto3" json:"contract_account,omitempty"`
	// Amount to claw back
	Amount        *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractClawback) Reset() {
	*x = ContractClawback{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractClawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractClawback) ProtoMessage() {}

func (x *ContractClawback) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractClawback.ProtoReflect.Descriptor instead.
func (*ContractClawback) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ContractClawback) GetContractAccount() string {
	if x != nil {
		return x.ContractAccount
	}
	return ""
}

func (x *ContractClawback) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// ContractUserDelete - Deletes user data from a contract
// Reference: https://xrpl.org/contractuserdelete.html
type ContractUserDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract account
	ContractAccount string `protobuf:"bytes,1,opt,name=contract_account,json=contractAccount,proto3" json:"contract_account,omitempty"`
	// Function to call for deletion
	FunctionName string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// (Optional) Parameters
	Parameters []string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Computation allowance
	ComputationAllowance uint64 `protobuf:"varint,4,opt,name=computation_allowance,json=computationAllowance,proto3" json:"computation_allowance,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContractUserDelete) Reset() {
	*x = ContractUserDelete{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractUserDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractUserDelete) ProtoMessage() {}

func (x *ContractUserDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractUserDelete.ProtoReflect.Descriptor instead.
func (*ContractUserDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ContractUserDelete) GetContractAccount() string {
	if x != nil {
		return x.ContractAccount
	}
	return ""
}

func (x *ContractUserDelete) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ContractUserDelete) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ContractUserDelete) GetComputationAllowance() uint64 {
	if x != nil {
		return x.ComputationAllowance
	}
	return 0
}

// ContractCall - Calls a smart contract function
// Reference: https://xrpl.org/contractcall.html
type ContractCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract account to call
	ContractAccount string `protobuf:"bytes,1,opt,name=contract_account,json=contractAccount,proto3" json:"contract_account,omitempty"`
	// Function name to invoke
	FunctionName string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// (Optional) Function parameters
	Parameters []string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Computation allowance
	ComputationAllowance uint64 `protobuf:"varint,4,opt,name=computation_allowance,json=computationAllowance,proto3" json:"computation_allowance,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContractCall) Reset() {
	*x = ContractCall{}
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCall) ProtoMessage() {}

func (x *ContractCall) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCall.ProtoReflect.Descriptor instead.
func (*ContractCall) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ContractCall) GetContractAccount() string {
	if x != nil {
		return x.ContractAccount
	}
	return ""
}

func (x *ContractCall) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ContractCall) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ContractCall) GetComputationAllowance() uint64 {
	if x != nil {
		return x.ComputationAllowance
	}
	return 0
}

var File_sf_xrpl_type_v1_contract_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_contract_proto_rawDesc = "" +
	"\n" +
	"\x1esf/xrpl/type/v1/contract.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"\x9a\x02\n" +
	"\x0eContractCreate\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x12#\n" +
	"\rcontract_hash\x18\x02 \x01(\tR\fcontractHash\x12?\n" +
	"\tfunctions\x18\x03 \x03(\v2!.sf.xrpl.type.v1.ContractFunctionR\tfunctions\x12/\n" +
	"\x13instance_parameters\x18\x04 \x03(\tR\x12instanceParameters\x12:\n" +
	"\x19instance_parameter_values\x18\x05 \x03(\tR\x17instanceParameterValues\x12\x10\n" +
	"\x03uri\x18\x06 \x01(\tR\x03uri\"F\n" +
	"\x10ContractFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\"\xdb\x02\n" +
	"\x0eContractModify\x12)\n" +
	"\x10contract_account\x18\x01 \x01(\tR\x0fcontractAccount\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rcontract_code\x18\x03 \x01(\tR\fcontractCode\x12#\n" +
	"\rcontract_hash\x18\x04 \x01(\tR\fcontractHash\x12?\n" +
	"\tfunctions\x18\x05 \x03(\v2!.sf.xrpl.type.v1.ContractFunctionR\tfunctions\x12/\n" +
	"\x13instance_parameters\x18\x06 \x03(\tR\x12instanceParameters\x12:\n" +
	"\x19instance_parameter_values\x18\a \x03(\tR\x17instanceParameterValues\x12\x10\n" +
	"\x03uri\x18\b \x01(\tR\x03uri\";\n" +
	"\x0eContractDelete\x12)\n" +
	"\x10contract_account\x18\x01 \x01(\tR\x0fcontractAccount\"n\n" +
	"\x10ContractClawback\x12)\n" +
	"\x10contract_account\x18\x01 \x01(\tR\x0fcontractAccount\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\"\xb9\x01\n" +
	"\x12ContractUserDelete\x12)\n" +
	"\x10contract_account\x18\x01 \x01(\tR\x0fcontractAccount\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\x123\n" +
	"\x15computation_allowance\x18\x04 \x01(\x04R\x14computationAllowance\"\xb3\x01\n" +
	"\fContractCall\x12)\n" +
	"\x10contract_account\x18\x01 \x01(\tR\x0fcontractAccount\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\x123\n" +
	"\x15computation_allowance\x18\x04 \x01(\x04R\x14computationAllowanceBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_contract_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_contract_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_contract_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_contract_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_contract_proto_rawDesc), len(file_sf_xrpl_type_v1_contract_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_contract_proto_rawDescData
}

var file_sf_xrpl_type_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sf_xrpl_type_v1_contract_proto_goTypes = []any{
	(*ContractCreate)(nil),     // 0: sf.xrpl.type.v1.ContractCreate
	(*ContractFunction)(nil),   // 1: sf.xrpl.type.v1.ContractFunction
	(*ContractModify)(nil),     // 2: sf.xrpl.type.v1.ContractModify
	(*ContractDelete)(nil),     // 3: sf.xrpl.type.v1.ContractDelete
	(*ContractClawback)(nil),   // 4: sf.xrpl.type.v1.ContractClawback
	(*ContractUserDelete)(nil), // 5: sf.xrpl.type.v1.ContractUserDelete
	(*ContractCall)(nil),       // 6: sf.xrpl.type.v1.ContractCall
	(*Amount)(nil),             // 7: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_contract_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.ContractCreate.functions:type_name -> sf.xrpl.type.v1.ContractFunction
	1, // 1: sf.xrpl.type.v1.ContractModify.functions:type_name -> sf.xrpl.type.v1.ContractFunction
	7, // 2: sf.xrpl.type.v1.ContractClawback.amount:type_name -> sf.xrpl.type.v1.Amount
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_contract_proto_init() }
func file_sf_xrpl_type_v1_contract_proto_init() {
	if File_sf_xrpl_type_v1_contract_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_contract_proto_rawDesc), len(file_sf_xrpl_type_v1_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_contract_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_contract_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_contract_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_contract_proto = out.File
	file_sf_xrpl_type_v1_contract_proto_goTypes = nil
	file_sf_xrpl_type_v1_contract_proto_depIdxs = nil
}
