// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/delegate.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DelegateSet - Delegates permissions to another account
// Reference: https://xrpl.org/delegateset.html
type DelegateSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account to delegate permissions to
	Authorize string `protobuf:"bytes,1,opt,name=authorize,proto3" json:"authorize,omitempty"`
	// List of permissions to delegate
	Permissions   []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateSet) Reset() {
	*x = DelegateSet{}
	mi := &file_sf_xrpl_type_v1_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateSet) ProtoMessage() {}

func (x *DelegateSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateSet.ProtoReflect.Descriptor instead.
func (*DelegateSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateSet) GetAuthorize() string {
	if x != nil {
		return x.Authorize
	}
	return ""
}

func (x *DelegateSet) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Permission type
	PermissionType uint32 `protobuf:"varint,1,opt,name=permission_type,json=permissionType,proto3" json:"permission_type,omitempty"`
	// (Optional) Permission value
	PermissionValue string `protobuf:"bytes,2,opt,name=permission_value,json=permissionValue,proto3" json:"permission_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_sf_xrpl_type_v1_delegate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_delegate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_delegate_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetPermissionType() uint32 {
	if x != nil {
		return x.PermissionType
	}
	return 0
}

func (x *Permission) GetPermissionValue() string {
	if x != nil {
		return x.PermissionValue
	}
	return ""
}

var File_sf_xrpl_type_v1_delegate_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_delegate_proto_rawDesc = "" +
	"\n" +
	"\x1esf/xrpl/type/v1/delegate.proto\x12\x0fsf.xrpl.type.v1\"j\n" +
	"\vDelegateSet\x12\x1c\n" +
	"\tauthorize\x18\x01 \x01(\tR\tauthorize\x12=\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1b.sf.xrpl.type.v1.PermissionR\vpermissions\"`\n" +
	"\n" +
	"Permission\x12'\n" +
	"\x0fpermission_type\x18\x01 \x01(\rR\x0epermissionType\x12)\n" +
	"\x10permission_value\x18\x02 \x01(\tR\x0fpermissionValueBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_delegate_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_delegate_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_delegate_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_delegate_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_delegate_proto_rawDesc), len(file_sf_xrpl_type_v1_delegate_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_delegate_proto_rawDescData
}

var file_sf_xrpl_type_v1_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_xrpl_type_v1_delegate_proto_goTypes = []any{
	(*DelegateSet)(nil), // 0: sf.xrpl.type.v1.DelegateSet
	(*Permission)(nil),  // 1: sf.xrpl.type.v1.Permission
}
var file_sf_xrpl_type_v1_delegate_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.DelegateSet.permissions:type_name -> sf.xrpl.type.v1.Permission
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_delegate_proto_init() }
func file_sf_xrpl_type_v1_delegate_proto_init() {
	if File_sf_xrpl_type_v1_delegate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_delegate_proto_rawDesc), len(file_sf_xrpl_type_v1_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_delegate_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_delegate_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_delegate_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_delegate_proto = out.File
	file_sf_xrpl_type_v1_delegate_proto_goTypes = nil
	file_sf_xrpl_type_v1_delegate_proto_depIdxs = nil
}
