// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/escrow.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EscrowCreate - Creates a held payment
// Reference: https://xrpl.org/escrowcreate.html
type EscrowCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount to escrow
	Amount *Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Recipient of escrowed funds
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// (Optional) Time after which escrow can be cancelled
	CancelAfter uint32 `protobuf:"varint,3,opt,name=cancel_after,json=cancelAfter,proto3" json:"cancel_after,omitempty"`
	// (Optional) Time after which escrow can be finished
	FinishAfter uint32 `protobuf:"varint,4,opt,name=finish_after,json=finishAfter,proto3" json:"finish_after,omitempty"`
	// (Optional) Crypto-condition that must be fulfilled (hex)
	Condition string `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	// (Optional) Destination tag
	DestinationTag uint32 `protobuf:"varint,6,opt,name=destination_tag,json=destinationTag,proto3" json:"destination_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EscrowCreate) Reset() {
	*x = EscrowCreate{}
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowCreate) ProtoMessage() {}

func (x *EscrowCreate) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowCreate.ProtoReflect.Descriptor instead.
func (*EscrowCreate) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_escrow_proto_rawDescGZIP(), []int{0}
}

func (x *EscrowCreate) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *EscrowCreate) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *EscrowCreate) GetCancelAfter() uint32 {
	if x != nil {
		return x.CancelAfter
	}
	return 0
}

func (x *EscrowCreate) GetFinishAfter() uint32 {
	if x != nil {
		return x.FinishAfter
	}
	return 0
}

func (x *EscrowCreate) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *EscrowCreate) GetDestinationTag() uint32 {
	if x != nil {
		return x.DestinationTag
	}
	return 0
}

// EscrowFinish - Completes a held payment
// Reference: https://xrpl.org/escrowfinish.html
type EscrowFinish struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner of the escrow
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Sequence of EscrowCreate transaction
	OfferSequence uint32 `protobuf:"varint,2,opt,name=offer_sequence,json=offerSequence,proto3" json:"offer_sequence,omitempty"`
	// (Optional) Crypto-condition (hex)
	Condition string `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	// (Optional) Fulfillment for condition (hex)
	Fulfillment   string `protobuf:"bytes,4,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowFinish) Reset() {
	*x = EscrowFinish{}
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowFinish) ProtoMessage() {}

func (x *EscrowFinish) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowFinish.ProtoReflect.Descriptor instead.
func (*EscrowFinish) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_escrow_proto_rawDescGZIP(), []int{1}
}

func (x *EscrowFinish) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *EscrowFinish) GetOfferSequence() uint32 {
	if x != nil {
		return x.OfferSequence
	}
	return 0
}

func (x *EscrowFinish) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *EscrowFinish) GetFulfillment() string {
	if x != nil {
		return x.Fulfillment
	}
	return ""
}

// EscrowCancel - Cancels a held payment
// Reference: https://xrpl.org/escrowcancel.html
type EscrowCancel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner of the escrow
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Sequence of EscrowCreate transaction
	OfferSequence uint32 `protobuf:"varint,2,opt,name=offer_sequence,json=offerSequence,proto3" json:"offer_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowCancel) Reset() {
	*x = EscrowCancel{}
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowCancel) ProtoMessage() {}

func (x *EscrowCancel) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_escrow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowCancel.ProtoReflect.Descriptor instead.
func (*EscrowCancel) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_escrow_proto_rawDescGZIP(), []int{2}
}

func (x *EscrowCancel) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *EscrowCancel) GetOfferSequence() uint32 {
	if x != nil {
		return x.OfferSequence
	}
	return 0
}

var File_sf_xrpl_type_v1_escrow_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_escrow_proto_rawDesc = "" +
	"\n" +
	"\x1csf/xrpl/type/v1/escrow.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"\xee\x01\n" +
	"\fEscrowCreate\x12/\n" +
	"\x06amount\x18\x01 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12!\n" +
	"\fcancel_after\x18\x03 \x01(\rR\vcancelAfter\x12!\n" +
	"\ffinish_after\x18\x04 \x01(\rR\vfinishAfter\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12'\n" +
	"\x0fdestination_tag\x18\x06 \x01(\rR\x0edestinationTag\"\x8b\x01\n" +
	"\fEscrowFinish\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eoffer_sequence\x18\x02 \x01(\rR\rofferSequence\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x12 \n" +
	"\vfulfillment\x18\x04 \x01(\tR\vfulfillment\"K\n" +
	"\fEscrowCancel\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eoffer_sequence\x18\x02 \x01(\rR\rofferSequenceBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_escrow_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_escrow_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_escrow_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_escrow_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_escrow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_escrow_proto_rawDesc), len(file_sf_xrpl_type_v1_escrow_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_escrow_proto_rawDescData
}

var file_sf_xrpl_type_v1_escrow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_xrpl_type_v1_escrow_proto_goTypes = []any{
	(*EscrowCreate)(nil), // 0: sf.xrpl.type.v1.EscrowCreate
	(*EscrowFinish)(nil), // 1: sf.xrpl.type.v1.EscrowFinish
	(*EscrowCancel)(nil), // 2: sf.xrpl.type.v1.EscrowCancel
	(*Amount)(nil),       // 3: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_escrow_proto_depIdxs = []int32{
	3, // 0: sf.xrpl.type.v1.EscrowCreate.amount:type_name -> sf.xrpl.type.v1.Amount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_escrow_proto_init() }
func file_sf_xrpl_type_v1_escrow_proto_init() {
	if File_sf_xrpl_type_v1_escrow_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_escrow_proto_rawDesc), len(file_sf_xrpl_type_v1_escrow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_escrow_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_escrow_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_escrow_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_escrow_proto = out.File
	file_sf_xrpl_type_v1_escrow_proto_goTypes = nil
	file_sf_xrpl_type_v1_escrow_proto_depIdxs = nil
}
