// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/lending.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoanBrokerSet - Creates or updates a Loan Broker
// An update is performed when loan_broker_id is set; otherwise a new broker is
// created over the referenced vault.
// Reference: https://xrpl.org/loanbrokerset.html
type LoanBrokerSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ledger entry ID the broker draws liquidity from (hex)
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// (Optional) Loan Broker ledger entry ID to update (hex); absent on create
	LoanBrokerId string `protobuf:"bytes,2,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	// (Optional) Arbitrary data associated with the broker (hex)
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// (Optional) Management fee rate, in 1/10 basis points
	ManagementFeeRate uint32 `protobuf:"varint,4,opt,name=management_fee_rate,json=managementFeeRate,proto3" json:"management_fee_rate,omitempty"`
	// (Optional) Maximum outstanding debt the broker may issue
	// STNumber, serialized as a decimal/scientific string
	DebtMaximum string `protobuf:"bytes,5,opt,name=debt_maximum,json=debtMaximum,proto3" json:"debt_maximum,omitempty"`
	// (Optional) Minimum first-loss-cover rate, in 1/10 basis points
	CoverRateMinimum uint32 `protobuf:"varint,6,opt,name=cover_rate_minimum,json=coverRateMinimum,proto3" json:"cover_rate_minimum,omitempty"`
	// (Optional) Liquidation cover rate, in 1/10 basis points
	CoverRateLiquidation uint32 `protobuf:"varint,7,opt,name=cover_rate_liquidation,json=coverRateLiquidation,proto3" json:"cover_rate_liquidation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoanBrokerSet) Reset() {
	*x = LoanBrokerSet{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanBrokerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanBrokerSet) ProtoMessage() {}

func (x *LoanBrokerSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanBrokerSet.ProtoReflect.Descriptor instead.
func (*LoanBrokerSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{0}
}

func (x *LoanBrokerSet) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *LoanBrokerSet) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

func (x *LoanBrokerSet) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LoanBrokerSet) GetManagementFeeRate() uint32 {
	if x != nil {
		return x.ManagementFeeRate
	}
	return 0
}

func (x *LoanBrokerSet) GetDebtMaximum() string {
	if x != nil {
		return x.DebtMaximum
	}
	return ""
}

func (x *LoanBrokerSet) GetCoverRateMinimum() uint32 {
	if x != nil {
		return x.CoverRateMinimum
	}
	return 0
}

func (x *LoanBrokerSet) GetCoverRateLiquidation() uint32 {
	if x != nil {
		return x.CoverRateLiquidation
	}
	return 0
}

// LoanBrokerDelete - Deletes an empty Loan Broker
// Reference: https://xrpl.org/loanbrokerdelete.html
type LoanBrokerDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan Broker ledger entry ID to delete (hex)
	LoanBrokerId  string `protobuf:"bytes,1,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanBrokerDelete) Reset() {
	*x = LoanBrokerDelete{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanBrokerDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanBrokerDelete) ProtoMessage() {}

func (x *LoanBrokerDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanBrokerDelete.ProtoReflect.Descriptor instead.
func (*LoanBrokerDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{1}
}

func (x *LoanBrokerDelete) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

// LoanBrokerCoverDeposit - Deposits first-loss capital into a Loan Broker
// Reference: https://xrpl.org/loanbrokercoverdeposit.html
type LoanBrokerCoverDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan Broker ledger entry ID (hex)
	LoanBrokerId string `protobuf:"bytes,1,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	// Amount of cover to deposit
	Amount        *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanBrokerCoverDeposit) Reset() {
	*x = LoanBrokerCoverDeposit{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanBrokerCoverDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanBrokerCoverDeposit) ProtoMessage() {}

func (x *LoanBrokerCoverDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanBrokerCoverDeposit.ProtoReflect.Descriptor instead.
func (*LoanBrokerCoverDeposit) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{2}
}

func (x *LoanBrokerCoverDeposit) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

func (x *LoanBrokerCoverDeposit) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// LoanBrokerCoverWithdraw - Withdraws first-loss capital from a Loan Broker
// Reference: https://xrpl.org/loanbrokercoverwithdraw.html
type LoanBrokerCoverWithdraw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan Broker ledger entry ID (hex)
	LoanBrokerId string `protobuf:"bytes,1,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	// Amount of cover to withdraw
	Amount *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// (Optional) Account to receive the withdrawn cover (defaults to sender)
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	// (Optional) Destination tag for the recipient
	DestinationTag uint32 `protobuf:"varint,4,opt,name=destination_tag,json=destinationTag,proto3" json:"destination_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoanBrokerCoverWithdraw) Reset() {
	*x = LoanBrokerCoverWithdraw{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanBrokerCoverWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanBrokerCoverWithdraw) ProtoMessage() {}

func (x *LoanBrokerCoverWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanBrokerCoverWithdraw.ProtoReflect.Descriptor instead.
func (*LoanBrokerCoverWithdraw) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{3}
}

func (x *LoanBrokerCoverWithdraw) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

func (x *LoanBrokerCoverWithdraw) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LoanBrokerCoverWithdraw) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *LoanBrokerCoverWithdraw) GetDestinationTag() uint32 {
	if x != nil {
		return x.DestinationTag
	}
	return 0
}

// LoanBrokerCoverClawback - Claws back first-loss capital from a Loan Broker
// Reference: https://xrpl.org/loanbrokercoverclawback.html
type LoanBrokerCoverClawback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Loan Broker ledger entry ID (hex)
	LoanBrokerId string `protobuf:"bytes,1,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	// (Optional) Amount of cover to claw back (zero/absent claws back all)
	Amount        *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanBrokerCoverClawback) Reset() {
	*x = LoanBrokerCoverClawback{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanBrokerCoverClawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanBrokerCoverClawback) ProtoMessage() {}

func (x *LoanBrokerCoverClawback) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanBrokerCoverClawback.ProtoReflect.Descriptor instead.
func (*LoanBrokerCoverClawback) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{4}
}

func (x *LoanBrokerCoverClawback) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

func (x *LoanBrokerCoverClawback) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// CounterpartySignature - Inner signature object authorizing a loan
// The borrower (counterparty) signs the loan terms; this object holds either a
// single signature (signing_pub_key + txn_signature) or a multi-signature
// (signers). It is excluded from the transaction's own signature.
type CounterpartySignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key used to create the single-signature (hex), empty if multi-signed
	SigningPubKey string `protobuf:"bytes,1,opt,name=signing_pub_key,json=signingPubKey,proto3" json:"signing_pub_key,omitempty"`
	// Single-signature over the loan terms (hex), empty if multi-signed
	TxnSignature string `protobuf:"bytes,2,opt,name=txn_signature,json=txnSignature,proto3" json:"txn_signature,omitempty"`
	// Multi-signature entries, empty if single-signed
	Signers       []*Signer `protobuf:"bytes,3,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartySignature) Reset() {
	*x = CounterpartySignature{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartySignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartySignature) ProtoMessage() {}

func (x *CounterpartySignature) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartySignature.ProtoReflect.Descriptor instead.
func (*CounterpartySignature) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{5}
}

func (x *CounterpartySignature) GetSigningPubKey() string {
	if x != nil {
		return x.SigningPubKey
	}
	return ""
}

func (x *CounterpartySignature) GetTxnSignature() string {
	if x != nil {
		return x.TxnSignature
	}
	return ""
}

func (x *CounterpartySignature) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

// LoanSet - Creates a Loan against a Loan Broker
// Reference: https://xrpl.org/loanset.html
type LoanSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan Broker ledger entry ID issuing the loan (hex)
	LoanBrokerId string `protobuf:"bytes,1,opt,name=loan_broker_id,json=loanBrokerId,proto3" json:"loan_broker_id,omitempty"`
	// (Optional) Arbitrary data associated with the loan (hex)
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// (Optional) Borrower account counterparty to the loan
	Counterparty string `protobuf:"bytes,3,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	// (Optional) Counterparty's signature authorizing the loan terms
	CounterpartySignature *CounterpartySignature `protobuf:"bytes,4,opt,name=counterparty_signature,json=counterpartySignature,proto3" json:"counterparty_signature,omitempty"`
	// (Optional) One-time loan origination fee
	// STNumber, serialized as a decimal/scientific string
	LoanOriginationFee string `protobuf:"bytes,5,opt,name=loan_origination_fee,json=loanOriginationFee,proto3" json:"loan_origination_fee,omitempty"`
	// (Optional) Periodic loan service fee
	// STNumber, serialized as a decimal/scientific string
	LoanServiceFee string `protobuf:"bytes,6,opt,name=loan_service_fee,json=loanServiceFee,proto3" json:"loan_service_fee,omitempty"`
	// (Optional) Fee charged on late payments
	// STNumber, serialized as a decimal/scientific string
	LatePaymentFee string `protobuf:"bytes,7,opt,name=late_payment_fee,json=latePaymentFee,proto3" json:"late_payment_fee,omitempty"`
	// (Optional) Fee charged on closing the loan
	// STNumber, serialized as a decimal/scientific string
	ClosePaymentFee string `protobuf:"bytes,8,opt,name=close_payment_fee,json=closePaymentFee,proto3" json:"close_payment_fee,omitempty"`
	// (Optional) Overpayment fee rate, in 1/10 basis points
	OverpaymentFee uint32 `protobuf:"varint,9,opt,name=overpayment_fee,json=overpaymentFee,proto3" json:"overpayment_fee,omitempty"`
	// (Optional) Interest rate, in 1/10 basis points
	InterestRate uint32 `protobuf:"varint,10,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	// (Optional) Late interest rate, in 1/10 basis points
	LateInterestRate uint32 `protobuf:"varint,11,opt,name=late_interest_rate,json=lateInterestRate,proto3" json:"late_interest_rate,omitempty"`
	// (Optional) Close interest rate, in 1/10 basis points
	CloseInterestRate uint32 `protobuf:"varint,12,opt,name=close_interest_rate,json=closeInterestRate,proto3" json:"close_interest_rate,omitempty"`
	// (Optional) Overpayment interest rate, in 1/10 basis points
	OverpaymentInterestRate uint32 `protobuf:"varint,13,opt,name=overpayment_interest_rate,json=overpaymentInterestRate,proto3" json:"overpayment_interest_rate,omitempty"`
	// Principal amount requested by the borrower
	// STNumber, serialized as a decimal/scientific string
	PrincipalRequested string `protobuf:"bytes,14,opt,name=principal_requested,json=principalRequested,proto3" json:"principal_requested,omitempty"`
	// (Optional) Total number of payments over the loan's life
	PaymentTotal uint32 `protobuf:"varint,15,opt,name=payment_total,json=paymentTotal,proto3" json:"payment_total,omitempty"`
	// (Optional) Interval between payments, in seconds
	PaymentInterval uint32 `protobuf:"varint,16,opt,name=payment_interval,json=paymentInterval,proto3" json:"payment_interval,omitempty"`
	// (Optional) Grace period before a payment is considered late, in seconds
	GracePeriod   uint32 `protobuf:"varint,17,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanSet) Reset() {
	*x = LoanSet{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanSet) ProtoMessage() {}

func (x *LoanSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanSet.ProtoReflect.Descriptor instead.
func (*LoanSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{6}
}

func (x *LoanSet) GetLoanBrokerId() string {
	if x != nil {
		return x.LoanBrokerId
	}
	return ""
}

func (x *LoanSet) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LoanSet) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *LoanSet) GetCounterpartySignature() *CounterpartySignature {
	if x != nil {
		return x.CounterpartySignature
	}
	return nil
}

func (x *LoanSet) GetLoanOriginationFee() string {
	if x != nil {
		return x.LoanOriginationFee
	}
	return ""
}

func (x *LoanSet) GetLoanServiceFee() string {
	if x != nil {
		return x.LoanServiceFee
	}
	return ""
}

func (x *LoanSet) GetLatePaymentFee() string {
	if x != nil {
		return x.LatePaymentFee
	}
	return ""
}

func (x *LoanSet) GetClosePaymentFee() string {
	if x != nil {
		return x.ClosePaymentFee
	}
	return ""
}

func (x *LoanSet) GetOverpaymentFee() uint32 {
	if x != nil {
		return x.OverpaymentFee
	}
	return 0
}

func (x *LoanSet) GetInterestRate() uint32 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *LoanSet) GetLateInterestRate() uint32 {
	if x != nil {
		return x.LateInterestRate
	}
	return 0
}

func (x *LoanSet) GetCloseInterestRate() uint32 {
	if x != nil {
		return x.CloseInterestRate
	}
	return 0
}

func (x *LoanSet) GetOverpaymentInterestRate() uint32 {
	if x != nil {
		return x.OverpaymentInterestRate
	}
	return 0
}

func (x *LoanSet) GetPrincipalRequested() string {
	if x != nil {
		return x.PrincipalRequested
	}
	return ""
}

func (x *LoanSet) GetPaymentTotal() uint32 {
	if x != nil {
		return x.PaymentTotal
	}
	return 0
}

func (x *LoanSet) GetPaymentInterval() uint32 {
	if x != nil {
		return x.PaymentInterval
	}
	return 0
}

func (x *LoanSet) GetGracePeriod() uint32 {
	if x != nil {
		return x.GracePeriod
	}
	return 0
}

// LoanDelete - Deletes a fully-repaid or defaulted Loan
// Reference: https://xrpl.org/loandelete.html
type LoanDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan ledger entry ID to delete (hex)
	LoanId        string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanDelete) Reset() {
	*x = LoanDelete{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanDelete) ProtoMessage() {}

func (x *LoanDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanDelete.ProtoReflect.Descriptor instead.
func (*LoanDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{7}
}

func (x *LoanDelete) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

// LoanManage - Manages a Loan's delinquency status (operations via Flags)
// Reference: https://xrpl.org/loanmanage.html
type LoanManage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan ledger entry ID to manage (hex)
	LoanId        string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanManage) Reset() {
	*x = LoanManage{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanManage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanManage) ProtoMessage() {}

func (x *LoanManage) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanManage.ProtoReflect.Descriptor instead.
func (*LoanManage) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{8}
}

func (x *LoanManage) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

// LoanPay - Makes a payment against a Loan
// Reference: https://xrpl.org/loanpay.html
type LoanPay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Loan ledger entry ID being paid (hex)
	LoanId string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	// Amount paid against the loan
	Amount        *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanPay) Reset() {
	*x = LoanPay{}
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanPay) ProtoMessage() {}

func (x *LoanPay) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_lending_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanPay.ProtoReflect.Descriptor instead.
func (*LoanPay) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_lending_proto_rawDescGZIP(), []int{9}
}

func (x *LoanPay) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *LoanPay) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_sf_xrpl_type_v1_lending_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_lending_proto_rawDesc = "" +
	"\n" +
	"\x1dsf/xrpl/type/v1/lending.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\x1a\x1csf/xrpl/type/v1/signer.proto\"\x9b\x02\n" +
	"\rLoanBrokerSet\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12$\n" +
	"\x0eloan_broker_id\x18\x02 \x01(\tR\floanBrokerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12.\n" +
	"\x13management_fee_rate\x18\x04 \x01(\rR\x11managementFeeRate\x12!\n" +
	"\fdebt_maximum\x18\x05 \x01(\tR\vdebtMaximum\x12,\n" +
	"\x12cover_rate_minimum\x18\x06 \x01(\rR\x10coverRateMinimum\x124\n" +
	"\x16cover_rate_liquidation\x18\a \x01(\rR\x14coverRateLiquidation\"8\n" +
	"\x10LoanBrokerDelete\x12$\n" +
	"\x0eloan_broker_id\x18\x01 \x01(\tR\floanBrokerId\"o\n" +
	"\x16LoanBrokerCoverDeposit\x12$\n" +
	"\x0eloan_broker_id\x18\x01 \x01(\tR\floanBrokerId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\"\xbb\x01\n" +
	"\x17LoanBrokerCoverWithdraw\x12$\n" +
	"\x0eloan_broker_id\x18\x01 \x01(\tR\floanBrokerId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12'\n" +
	"\x0fdestination_tag\x18\x04 \x01(\rR\x0edestinationTag\"p\n" +
	"\x17LoanBrokerCoverClawback\x12$\n" +
	"\x0eloan_broker_id\x18\x01 \x01(\tR\floanBrokerId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\"\x97\x01\n" +
	"\x15CounterpartySignature\x12&\n" +
	"\x0fsigning_pub_key\x18\x01 \x01(\tR\rsigningPubKey\x12#\n" +
	"\rtxn_signature\x18\x02 \x01(\tR\ftxnSignature\x121\n" +
	"\asigners\x18\x03 \x03(\v2\x17.sf.xrpl.type.v1.SignerR\asigners\"\x84\x06\n" +
	"\aLoanSet\x12$\n" +
	"\x0eloan_broker_id\x18\x01 \x01(\tR\floanBrokerId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\"\n" +
	"\fcounterparty\x18\x03 \x01(\tR\fcounterparty\x12]\n" +
	"\x16counterparty_signature\x18\x04 \x01(\v2&.sf.xrpl.type.v1.CounterpartySignatureR\x15counterpartySignature\x120\n" +
	"\x14loan_origination_fee\x18\x05 \x01(\tR\x12loanOriginationFee\x12(\n" +
	"\x10loan_service_fee\x18\x06 \x01(\tR\x0eloanServiceFee\x12(\n" +
	"\x10late_payment_fee\x18\a \x01(\tR\x0elatePaymentFee\x12*\n" +
	"\x11close_payment_fee\x18\b \x01(\tR\x0fclosePaymentFee\x12'\n" +
	"\x0foverpayment_fee\x18\t \x01(\rR\x0eoverpaymentFee\x12#\n" +
	"\rinterest_rate\x18\n" +
	" \x01(\rR\finterestRate\x12,\n" +
	"\x12late_interest_rate\x18\v \x01(\rR\x10lateInterestRate\x12.\n" +
	"\x13close_interest_rate\x18\f \x01(\rR\x11closeInterestRate\x12:\n" +
	"\x19overpayment_interest_rate\x18\r \x01(\rR\x17overpaymentInterestRate\x12/\n" +
	"\x13principal_requested\x18\x0e \x01(\tR\x12principalRequested\x12#\n" +
	"\rpayment_total\x18\x0f \x01(\rR\fpaymentTotal\x12)\n" +
	"\x10payment_interval\x18\x10 \x01(\rR\x0fpaymentInterval\x12!\n" +
	"\fgrace_period\x18\x11 \x01(\rR\vgracePeriod\"%\n" +
	"\n" +
	"LoanDelete\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"%\n" +
	"\n" +
	"LoanManage\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"S\n" +
	"\aLoanPay\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amountBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_lending_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_lending_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_lending_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_lending_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_lending_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_lending_proto_rawDesc), len(file_sf_xrpl_type_v1_lending_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_lending_proto_rawDescData
}

var file_sf_xrpl_type_v1_lending_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sf_xrpl_type_v1_lending_proto_goTypes = []any{
	(*LoanBrokerSet)(nil),           // 0: sf.xrpl.type.v1.LoanBrokerSet
	(*LoanBrokerDelete)(nil),        // 1: sf.xrpl.type.v1.LoanBrokerDelete
	(*LoanBrokerCoverDeposit)(nil),  // 2: sf.xrpl.type.v1.LoanBrokerCoverDeposit
	(*LoanBrokerCoverWithdraw)(nil), // 3: sf.xrpl.type.v1.LoanBrokerCoverWithdraw
	(*LoanBrokerCoverClawback)(nil), // 4: sf.xrpl.type.v1.LoanBrokerCoverClawback
	(*CounterpartySignature)(nil),   // 5: sf.xrpl.type.v1.CounterpartySignature
	(*LoanSet)(nil),                 // 6: sf.xrpl.type.v1.LoanSet
	(*LoanDelete)(nil),              // 7: sf.xrpl.type.v1.LoanDelete
	(*LoanManage)(nil),              // 8: sf.xrpl.type.v1.LoanManage
	(*LoanPay)(nil),                 // 9: sf.xrpl.type.v1.LoanPay
	(*Amount)(nil),                  // 10: sf.xrpl.type.v1.Amount
	(*Signer)(nil),                  // 11: sf.xrpl.type.v1.Signer
}
var file_sf_xrpl_type_v1_lending_proto_depIdxs = []int32{
	10, // 0: sf.xrpl.type.v1.LoanBrokerCoverDeposit.amount:type_name -> sf.xrpl.type.v1.Amount
	10, // 1: sf.xrpl.type.v1.LoanBrokerCoverWithdraw.amount:type_name -> sf.xrpl.type.v1.Amount
	10, // 2: sf.xrpl.type.v1.LoanBrokerCoverClawback.amount:type_name -> sf.xrpl.type.v1.Amount
	11, // 3: sf.xrpl.type.v1.CounterpartySignature.signers:type_name -> sf.xrpl.type.v1.Signer
	5,  // 4: sf.xrpl.type.v1.LoanSet.counterparty_signature:type_name -> sf.xrpl.type.v1.CounterpartySignature
	10, // 5: sf.xrpl.type.v1.LoanPay.amount:type_name -> sf.xrpl.type.v1.Amount
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_lending_proto_init() }
func file_sf_xrpl_type_v1_lending_proto_init() {
	if File_sf_xrpl_type_v1_lending_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	file_sf_xrpl_type_v1_signer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_lending_proto_rawDesc), len(file_sf_xrpl_type_v1_lending_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_lending_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_lending_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_lending_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_lending_proto = out.File
	file_sf_xrpl_type_v1_lending_proto_goTypes = nil
	file_sf_xrpl_type_v1_lending_proto_depIdxs = nil
}
