// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/mptoken.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MPTokenIssuanceCreate - Creates a Multi-Purpose Token issuance
// Reference: https://xrpl.org/mptokenissuancecreate.html
type MPTokenIssuanceCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Decimal scale of the token
	AssetScale uint32 `protobuf:"varint,1,opt,name=asset_scale,json=assetScale,proto3" json:"asset_scale,omitempty"`
	// (Optional) Transfer fee (0-50000, 0-50%)
	TransferFee uint32 `protobuf:"varint,2,opt,name=transfer_fee,json=transferFee,proto3" json:"transfer_fee,omitempty"`
	// (Optional) Maximum token supply
	MaximumAmount uint64 `protobuf:"varint,3,opt,name=maximum_amount,json=maximumAmount,proto3" json:"maximum_amount,omitempty"`
	// (Optional) Metadata for the token (hex)
	MptokenMetadata string `protobuf:"bytes,4,opt,name=mptoken_metadata,json=mptokenMetadata,proto3" json:"mptoken_metadata,omitempty"`
	// (Optional) Transaction flags
	// tfMPTCanLock = 2 (0x00000002) - MPT can be locked individually and globally
	// tfMPTRequireAuth = 4 (0x00000004) - Individual holders must be authorized
	// tfMPTCanEscrow = 8 (0x00000008) - Holders can place balances into escrow
	// tfMPTCanTrade = 16 (0x00000010) - Holders can trade balances using DEX
	// tfMPTCanTransfer = 32 (0x00000020) - Tokens can be transferred to non-issuers
	// tfMPTCanClawback = 64 (0x00000040) - Issuer can claw back value from holders
	Flags         uint32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPTokenIssuanceCreate) Reset() {
	*x = MPTokenIssuanceCreate{}
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPTokenIssuanceCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPTokenIssuanceCreate) ProtoMessage() {}

func (x *MPTokenIssuanceCreate) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPTokenIssuanceCreate.ProtoReflect.Descriptor instead.
func (*MPTokenIssuanceCreate) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_mptoken_proto_rawDescGZIP(), []int{0}
}

func (x *MPTokenIssuanceCreate) GetAssetScale() uint32 {
	if x != nil {
		return x.AssetScale
	}
	return 0
}

func (x *MPTokenIssuanceCreate) GetTransferFee() uint32 {
	if x != nil {
		return x.TransferFee
	}
	return 0
}

func (x *MPTokenIssuanceCreate) GetMaximumAmount() uint64 {
	if x != nil {
		return x.MaximumAmount
	}
	return 0
}

func (x *MPTokenIssuanceCreate) GetMptokenMetadata() string {
	if x != nil {
		return x.MptokenMetadata
	}
	return ""
}

func (x *MPTokenIssuanceCreate) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// MPTokenIssuanceDestroy - Destroys an MPToken issuance
// Reference: https://xrpl.org/mptokenissuancedestroy.html
type MPTokenIssuanceDestroy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the issuance to destroy (64 hex chars)
	MptokenIssuanceId string `protobuf:"bytes,1,opt,name=mptoken_issuance_id,json=mptokenIssuanceId,proto3" json:"mptoken_issuance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MPTokenIssuanceDestroy) Reset() {
	*x = MPTokenIssuanceDestroy{}
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPTokenIssuanceDestroy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPTokenIssuanceDestroy) ProtoMessage() {}

func (x *MPTokenIssuanceDestroy) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPTokenIssuanceDestroy.ProtoReflect.Descriptor instead.
func (*MPTokenIssuanceDestroy) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_mptoken_proto_rawDescGZIP(), []int{1}
}

func (x *MPTokenIssuanceDestroy) GetMptokenIssuanceId() string {
	if x != nil {
		return x.MptokenIssuanceId
	}
	return ""
}

// MPTokenIssuanceSet - Sets properties on an MPToken issuance or holder
// Reference: https://xrpl.org/mptokenissuanceset.html
type MPTokenIssuanceSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the issuance
	MptokenIssuanceId string `protobuf:"bytes,1,opt,name=mptoken_issuance_id,json=mptokenIssuanceId,proto3" json:"mptoken_issuance_id,omitempty"`
	// (Optional) Holder to modify
	Holder string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// (Optional) Transaction flags
	// tfMPTLock = 1 (0x00000001) - Lock balances of this MPT issuance
	// tfMPTUnlock = 2 (0x00000002) - Unlock balances of this MPT issuance
	Flags         uint32 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPTokenIssuanceSet) Reset() {
	*x = MPTokenIssuanceSet{}
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPTokenIssuanceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPTokenIssuanceSet) ProtoMessage() {}

func (x *MPTokenIssuanceSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPTokenIssuanceSet.ProtoReflect.Descriptor instead.
func (*MPTokenIssuanceSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_mptoken_proto_rawDescGZIP(), []int{2}
}

func (x *MPTokenIssuanceSet) GetMptokenIssuanceId() string {
	if x != nil {
		return x.MptokenIssuanceId
	}
	return ""
}

func (x *MPTokenIssuanceSet) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *MPTokenIssuanceSet) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// MPTokenAuthorize - Authorizes an account to hold MPTokens
// Reference: https://xrpl.org/mptokenauthorize.html
type MPTokenAuthorize struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the issuance to authorize
	MptokenIssuanceId string `protobuf:"bytes,1,opt,name=mptoken_issuance_id,json=mptokenIssuanceId,proto3" json:"mptoken_issuance_id,omitempty"`
	// (Optional) Holder to authorize (issuer-side)
	Holder string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// (Optional) Transaction flags
	// tfMPTUnauthorize = 1 (0x00000001) - Revoke authorization/willingness to hold MPT
	Flags         uint32 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPTokenAuthorize) Reset() {
	*x = MPTokenAuthorize{}
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPTokenAuthorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPTokenAuthorize) ProtoMessage() {}

func (x *MPTokenAuthorize) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_mptoken_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPTokenAuthorize.ProtoReflect.Descriptor instead.
func (*MPTokenAuthorize) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_mptoken_proto_rawDescGZIP(), []int{3}
}

func (x *MPTokenAuthorize) GetMptokenIssuanceId() string {
	if x != nil {
		return x.MptokenIssuanceId
	}
	return ""
}

func (x *MPTokenAuthorize) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *MPTokenAuthorize) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

var File_sf_xrpl_type_v1_mptoken_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_mptoken_proto_rawDesc = "" +
	"\n" +
	"\x1dsf/xrpl/type/v1/mptoken.proto\x12\x0fsf.xrpl.type.v1\"\xc3\x01\n" +
	"\x15MPTokenIssuanceCreate\x12\x1f\n" +
	"\vasset_scale\x18\x01 \x01(\rR\n" +
	"assetScale\x12!\n" +
	"\ftransfer_fee\x18\x02 \x01(\rR\vtransferFee\x12%\n" +
	"\x0emaximum_amount\x18\x03 \x01(\x04R\rmaximumAmount\x12)\n" +
	"\x10mptoken_metadata\x18\x04 \x01(\tR\x0fmptokenMetadata\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"H\n" +
	"\x16MPTokenIssuanceDestroy\x12.\n" +
	"\x13mptoken_issuance_id\x18\x01 \x01(\tR\x11mptokenIssuanceId\"r\n" +
	"\x12MPTokenIssuanceSet\x12.\n" +
	"\x13mptoken_issuance_id\x18\x01 \x01(\tR\x11mptokenIssuanceId\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\"p\n" +
	"\x10MPTokenAuthorize\x12.\n" +
	"\x13mptoken_issuance_id\x18\x01 \x01(\tR\x11mptokenIssuanceId\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flagsBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_mptoken_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_mptoken_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_mptoken_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_mptoken_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_mptoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_mptoken_proto_rawDesc), len(file_sf_xrpl_type_v1_mptoken_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_mptoken_proto_rawDescData
}

var file_sf_xrpl_type_v1_mptoken_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_xrpl_type_v1_mptoken_proto_goTypes = []any{
	(*MPTokenIssuanceCreate)(nil),  // 0: sf.xrpl.type.v1.MPTokenIssuanceCreate
	(*MPTokenIssuanceDestroy)(nil), // 1: sf.xrpl.type.v1.MPTokenIssuanceDestroy
	(*MPTokenIssuanceSet)(nil),     // 2: sf.xrpl.type.v1.MPTokenIssuanceSet
	(*MPTokenAuthorize)(nil),       // 3: sf.xrpl.type.v1.MPTokenAuthorize
}
var file_sf_xrpl_type_v1_mptoken_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_mptoken_proto_init() }
func file_sf_xrpl_type_v1_mptoken_proto_init() {
	if File_sf_xrpl_type_v1_mptoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_mptoken_proto_rawDesc), len(file_sf_xrpl_type_v1_mptoken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_mptoken_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_mptoken_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_mptoken_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_mptoken_proto = out.File
	file_sf_xrpl_type_v1_mptoken_proto_goTypes = nil
	file_sf_xrpl_type_v1_mptoken_proto_depIdxs = nil
}
