// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/oracle.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OracleSet - Creates or updates a price oracle
// Reference: https://xrpl.org/oracleset.html
type OracleSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this oracle
	OracleDocumentId uint32 `protobuf:"varint,1,opt,name=oracle_document_id,json=oracleDocumentId,proto3" json:"oracle_document_id,omitempty"`
	// (Optional) Provider name (hex)
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// (Optional) URI for oracle data
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// (Optional) Asset class (hex)
	AssetClass string `protobuf:"bytes,4,opt,name=asset_class,json=assetClass,proto3" json:"asset_class,omitempty"`
	// Time of last update (Ripple epoch)
	LastUpdateTime uint32 `protobuf:"varint,5,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	// Price data series
	PriceDataSeries []*PriceData `protobuf:"bytes,6,rep,name=price_data_series,json=priceDataSeries,proto3" json:"price_data_series,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OracleSet) Reset() {
	*x = OracleSet{}
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleSet) ProtoMessage() {}

func (x *OracleSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleSet.ProtoReflect.Descriptor instead.
func (*OracleSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *OracleSet) GetOracleDocumentId() uint32 {
	if x != nil {
		return x.OracleDocumentId
	}
	return 0
}

func (x *OracleSet) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OracleSet) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *OracleSet) GetAssetClass() string {
	if x != nil {
		return x.AssetClass
	}
	return ""
}

func (x *OracleSet) GetLastUpdateTime() uint32 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *OracleSet) GetPriceDataSeries() []*PriceData {
	if x != nil {
		return x.PriceDataSeries
	}
	return nil
}

type PriceData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base asset
	BaseAsset string `protobuf:"bytes,1,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	// Quote asset
	QuoteAsset string `protobuf:"bytes,2,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	// (Optional) Asset price
	AssetPrice uint64 `protobuf:"varint,3,opt,name=asset_price,json=assetPrice,proto3" json:"asset_price,omitempty"`
	// (Optional) Scale factor
	Scale         uint32 `protobuf:"varint,4,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceData) Reset() {
	*x = PriceData{}
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceData) ProtoMessage() {}

func (x *PriceData) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceData.ProtoReflect.Descriptor instead.
func (*PriceData) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *PriceData) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *PriceData) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *PriceData) GetAssetPrice() uint64 {
	if x != nil {
		return x.AssetPrice
	}
	return 0
}

func (x *PriceData) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// OracleDelete - Deletes a price oracle
// Reference: https://xrpl.org/oracledelete.html
type OracleDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of oracle to delete
	OracleDocumentId uint32 `protobuf:"varint,1,opt,name=oracle_document_id,json=oracleDocumentId,proto3" json:"oracle_document_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OracleDelete) Reset() {
	*x = OracleDelete{}
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleDelete) ProtoMessage() {}

func (x *OracleDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleDelete.ProtoReflect.Descriptor instead.
func (*OracleDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *OracleDelete) GetOracleDocumentId() uint32 {
	if x != nil {
		return x.OracleDocumentId
	}
	return 0
}

var File_sf_xrpl_type_v1_oracle_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"\x1csf/xrpl/type/v1/oracle.proto\x12\x0fsf.xrpl.type.v1\"\xfa\x01\n" +
	"\tOracleSet\x12,\n" +
	"\x12oracle_document_id\x18\x01 \x01(\rR\x10oracleDocumentId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1f\n" +
	"\vasset_class\x18\x04 \x01(\tR\n" +
	"assetClass\x12(\n" +
	"\x10last_update_time\x18\x05 \x01(\rR\x0elastUpdateTime\x12F\n" +
	"\x11price_data_series\x18\x06 \x03(\v2\x1a.sf.xrpl.type.v1.PriceDataR\x0fpriceDataSeries\"\x82\x01\n" +
	"\tPriceData\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x01 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x02 \x01(\tR\n" +
	"quoteAsset\x12\x1f\n" +
	"\vasset_price\x18\x03 \x01(\x04R\n" +
	"assetPrice\x12\x14\n" +
	"\x05scale\x18\x04 \x01(\rR\x05scale\"<\n" +
	"\fOracleDelete\x12,\n" +
	"\x12oracle_document_id\x18\x01 \x01(\rR\x10oracleDocumentIdBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_oracle_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_oracle_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_oracle_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_oracle_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_oracle_proto_rawDesc), len(file_sf_xrpl_type_v1_oracle_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_oracle_proto_rawDescData
}

var file_sf_xrpl_type_v1_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_xrpl_type_v1_oracle_proto_goTypes = []any{
	(*OracleSet)(nil),    // 0: sf.xrpl.type.v1.OracleSet
	(*PriceData)(nil),    // 1: sf.xrpl.type.v1.PriceData
	(*OracleDelete)(nil), // 2: sf.xrpl.type.v1.OracleDelete
}
var file_sf_xrpl_type_v1_oracle_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.OracleSet.price_data_series:type_name -> sf.xrpl.type.v1.PriceData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_oracle_proto_init() }
func file_sf_xrpl_type_v1_oracle_proto_init() {
	if File_sf_xrpl_type_v1_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_oracle_proto_rawDesc), len(file_sf_xrpl_type_v1_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_oracle_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_oracle_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_oracle_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_oracle_proto = out.File
	file_sf_xrpl_type_v1_oracle_proto_goTypes = nil
	file_sf_xrpl_type_v1_oracle_proto_depIdxs = nil
}
