// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/signer.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signer in a multi-signature
// Used in both transaction signers field and batch signers
type Signer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address associated with this signature, as it appears in the signer list
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Signature for this transaction, verifiable using the signing_pub_key
	TxnSignature string `protobuf:"bytes,2,opt,name=txn_signature,json=txnSignature,proto3" json:"txn_signature,omitempty"`
	// Public key used to create this signature
	SigningPubKey string `protobuf:"bytes,3,opt,name=signing_pub_key,json=signingPubKey,proto3" json:"signing_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signer) Reset() {
	*x = Signer{}
	mi := &file_sf_xrpl_type_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signer) ProtoMessage() {}

func (x *Signer) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signer.ProtoReflect.Descriptor instead.
func (*Signer) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_signer_proto_rawDescGZIP(), []int{0}
}

func (x *Signer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Signer) GetTxnSignature() string {
	if x != nil {
		return x.TxnSignature
	}
	return ""
}

func (x *Signer) GetSigningPubKey() string {
	if x != nil {
		return x.SigningPubKey
	}
	return ""
}

var File_sf_xrpl_type_v1_signer_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_signer_proto_rawDesc = "" +
	"\n" +
	"\x1csf/xrpl/type/v1/signer.proto\x12\x0fsf.xrpl.type.v1\"o\n" +
	"\x06Signer\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12#\n" +
	"\rtxn_signature\x18\x02 \x01(\tR\ftxnSignature\x12&\n" +
	"\x0fsigning_pub_key\x18\x03 \x01(\tR\rsigningPubKeyBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_signer_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_signer_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_signer_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_signer_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_signer_proto_rawDesc), len(file_sf_xrpl_type_v1_signer_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_signer_proto_rawDescData
}

var file_sf_xrpl_type_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sf_xrpl_type_v1_signer_proto_goTypes = []any{
	(*Signer)(nil), // 0: sf.xrpl.type.v1.Signer
}
var file_sf_xrpl_type_v1_signer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_signer_proto_init() }
func file_sf_xrpl_type_v1_signer_proto_init() {
	if File_sf_xrpl_type_v1_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_signer_proto_rawDesc), len(file_sf_xrpl_type_v1_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_signer_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_signer_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_signer_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_signer_proto = out.File
	file_sf_xrpl_type_v1_signer_proto_goTypes = nil
	file_sf_xrpl_type_v1_signer_proto_depIdxs = nil
}
