// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/system.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnableAmendment - System transaction to enable/modify amendments
// Reference: https://xrpl.org/enableamendment.html
type EnableAmendment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger sequence when this applies
	LedgerSequence uint32 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Amendment hash (64 hex chars)
	Amendment     string `protobuf:"bytes,2,opt,name=amendment,proto3" json:"amendment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableAmendment) Reset() {
	*x = EnableAmendment{}
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableAmendment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAmendment) ProtoMessage() {}

func (x *EnableAmendment) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAmendment.ProtoReflect.Descriptor instead.
func (*EnableAmendment) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *EnableAmendment) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EnableAmendment) GetAmendment() string {
	if x != nil {
		return x.Amendment
	}
	return ""
}

// SetFee - System transaction to update network fees
// Reference: https://xrpl.org/setfee.html
type SetFee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Ledger sequence when this applies
	LedgerSequence uint32 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Old format fields
	BaseFee           uint64 `protobuf:"varint,2,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	ReferenceFeeUnits uint32 `protobuf:"varint,3,opt,name=reference_fee_units,json=referenceFeeUnits,proto3" json:"reference_fee_units,omitempty"`
	ReserveBase       uint32 `protobuf:"varint,4,opt,name=reserve_base,json=reserveBase,proto3" json:"reserve_base,omitempty"`
	ReserveIncrement  uint32 `protobuf:"varint,5,opt,name=reserve_increment,json=reserveIncrement,proto3" json:"reserve_increment,omitempty"`
	// New format fields (drops)
	BaseFeeDrops          *Amount `protobuf:"bytes,6,opt,name=base_fee_drops,json=baseFeeDrops,proto3" json:"base_fee_drops,omitempty"`
	ReserveBaseDrops      *Amount `protobuf:"bytes,7,opt,name=reserve_base_drops,json=reserveBaseDrops,proto3" json:"reserve_base_drops,omitempty"`
	ReserveIncrementDrops *Amount `protobuf:"bytes,8,opt,name=reserve_increment_drops,json=reserveIncrementDrops,proto3" json:"reserve_increment_drops,omitempty"`
	// Smart contract related
	ExtensionComputeLimit uint64 `protobuf:"varint,9,opt,name=extension_compute_limit,json=extensionComputeLimit,proto3" json:"extension_compute_limit,omitempty"`
	ExtensionSizeLimit    uint64 `protobuf:"varint,10,opt,name=extension_size_limit,json=extensionSizeLimit,proto3" json:"extension_size_limit,omitempty"`
	GasPrice              uint64 `protobuf:"varint,11,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetFee) Reset() {
	*x = SetFee{}
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFee) ProtoMessage() {}

func (x *SetFee) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFee.ProtoReflect.Descriptor instead.
func (*SetFee) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *SetFee) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *SetFee) GetBaseFee() uint64 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

func (x *SetFee) GetReferenceFeeUnits() uint32 {
	if x != nil {
		return x.ReferenceFeeUnits
	}
	return 0
}

func (x *SetFee) GetReserveBase() uint32 {
	if x != nil {
		return x.ReserveBase
	}
	return 0
}

func (x *SetFee) GetReserveIncrement() uint32 {
	if x != nil {
		return x.ReserveIncrement
	}
	return 0
}

func (x *SetFee) GetBaseFeeDrops() *Amount {
	if x != nil {
		return x.BaseFeeDrops
	}
	return nil
}

func (x *SetFee) GetReserveBaseDrops() *Amount {
	if x != nil {
		return x.ReserveBaseDrops
	}
	return nil
}

func (x *SetFee) GetReserveIncrementDrops() *Amount {
	if x != nil {
		return x.ReserveIncrementDrops
	}
	return nil
}

func (x *SetFee) GetExtensionComputeLimit() uint64 {
	if x != nil {
		return x.ExtensionComputeLimit
	}
	return 0
}

func (x *SetFee) GetExtensionSizeLimit() uint64 {
	if x != nil {
		return x.ExtensionSizeLimit
	}
	return 0
}

func (x *SetFee) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

// UNLModify - System transaction to modify the Unique Node List
// Reference: https://xrpl.org/unlmodify.html
type UNLModify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this disables a validator
	UnlModifyDisabling bool `protobuf:"varint,1,opt,name=unl_modify_disabling,json=unlModifyDisabling,proto3" json:"unl_modify_disabling,omitempty"`
	// Ledger sequence when this applies
	LedgerSequence uint32 `protobuf:"varint,2,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Validator public key being modified (hex)
	UnlModifyValidator string `protobuf:"bytes,3,opt,name=unl_modify_validator,json=unlModifyValidator,proto3" json:"unl_modify_validator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UNLModify) Reset() {
	*x = UNLModify{}
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNLModify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNLModify) ProtoMessage() {}

func (x *UNLModify) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNLModify.ProtoReflect.Descriptor instead.
func (*UNLModify) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *UNLModify) GetUnlModifyDisabling() bool {
	if x != nil {
		return x.UnlModifyDisabling
	}
	return false
}

func (x *UNLModify) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *UNLModify) GetUnlModifyValidator() string {
	if x != nil {
		return x.UnlModifyValidator
	}
	return ""
}

// LedgerStateFix - System transaction to fix ledger state issues
// Reference: https://xrpl.org/ledgerstatefix.html
type LedgerStateFix struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of fix to apply
	LedgerFixType uint32 `protobuf:"varint,1,opt,name=ledger_fix_type,json=ledgerFixType,proto3" json:"ledger_fix_type,omitempty"`
	// (Optional) Owner account affected
	Owner         string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerStateFix) Reset() {
	*x = LedgerStateFix{}
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerStateFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerStateFix) ProtoMessage() {}

func (x *LedgerStateFix) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerStateFix.ProtoReflect.Descriptor instead.
func (*LedgerStateFix) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *LedgerStateFix) GetLedgerFixType() uint32 {
	if x != nil {
		return x.LedgerFixType
	}
	return 0
}

func (x *LedgerStateFix) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_sf_xrpl_type_v1_system_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x1csf/xrpl/type/v1/system.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"X\n" +
	"\x0fEnableAmendment\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12\x1c\n" +
	"\tamendment\x18\x02 \x01(\tR\tamendment\"\xaa\x04\n" +
	"\x06SetFee\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12\x19\n" +
	"\bbase_fee\x18\x02 \x01(\x04R\abaseFee\x12.\n" +
	"\x13reference_fee_units\x18\x03 \x01(\rR\x11referenceFeeUnits\x12!\n" +
	"\freserve_base\x18\x04 \x01(\rR\vreserveBase\x12+\n" +
	"\x11reserve_increment\x18\x05 \x01(\rR\x10reserveIncrement\x12=\n" +
	"\x0ebase_fee_drops\x18\x06 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\fbaseFeeDrops\x12E\n" +
	"\x12reserve_base_drops\x18\a \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x10reserveBaseDrops\x12O\n" +
	"\x17reserve_increment_drops\x18\b \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x15reserveIncrementDrops\x126\n" +
	"\x17extension_compute_limit\x18\t \x01(\x04R\x15extensionComputeLimit\x120\n" +
	"\x14extension_size_limit\x18\n" +
	" \x01(\x04R\x12extensionSizeLimit\x12\x1b\n" +
	"\tgas_price\x18\v \x01(\x04R\bgasPrice\"\x98\x01\n" +
	"\tUNLModify\x120\n" +
	"\x14unl_modify_disabling\x18\x01 \x01(\bR\x12unlModifyDisabling\x12'\n" +
	"\x0fledger_sequence\x18\x02 \x01(\rR\x0eledgerSequence\x120\n" +
	"\x14unl_modify_validator\x18\x03 \x01(\tR\x12unlModifyValidator\"N\n" +
	"\x0eLedgerStateFix\x12&\n" +
	"\x0fledger_fix_type\x18\x01 \x01(\rR\rledgerFixType\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05ownerBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_system_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_system_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_system_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_system_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_system_proto_rawDesc), len(file_sf_xrpl_type_v1_system_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_system_proto_rawDescData
}

var file_sf_xrpl_type_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_xrpl_type_v1_system_proto_goTypes = []any{
	(*EnableAmendment)(nil), // 0: sf.xrpl.type.v1.EnableAmendment
	(*SetFee)(nil),          // 1: sf.xrpl.type.v1.SetFee
	(*UNLModify)(nil),       // 2: sf.xrpl.type.v1.UNLModify
	(*LedgerStateFix)(nil),  // 3: sf.xrpl.type.v1.LedgerStateFix
	(*Amount)(nil),          // 4: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_system_proto_depIdxs = []int32{
	4, // 0: sf.xrpl.type.v1.SetFee.base_fee_drops:type_name -> sf.xrpl.type.v1.Amount
	4, // 1: sf.xrpl.type.v1.SetFee.reserve_base_drops:type_name -> sf.xrpl.type.v1.Amount
	4, // 2: sf.xrpl.type.v1.SetFee.reserve_increment_drops:type_name -> sf.xrpl.type.v1.Amount
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_system_proto_init() }
func file_sf_xrpl_type_v1_system_proto_init() {
	if File_sf_xrpl_type_v1_system_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_system_proto_rawDesc), len(file_sf_xrpl_type_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_system_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_system_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_system_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_system_proto = out.File
	file_sf_xrpl_type_v1_system_proto_goTypes = nil
	file_sf_xrpl_type_v1_system_proto_depIdxs = nil
}
