// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/trustline.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrustSet - Creates or modifies a trust line
// Reference: https://xrpl.org/trustset.html
type TrustSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The limit of the trust line (currency/issuer defines the line)
	LimitAmount *Amount `protobuf:"bytes,1,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	// (Optional) Incoming value transfer fee (0-100%, scaled by 1 billion)
	QualityIn uint32 `protobuf:"varint,2,opt,name=quality_in,json=qualityIn,proto3" json:"quality_in,omitempty"`
	// (Optional) Outgoing value transfer fee
	QualityOut    uint32 `protobuf:"varint,3,opt,name=quality_out,json=qualityOut,proto3" json:"quality_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustSet) Reset() {
	*x = TrustSet{}
	mi := &file_sf_xrpl_type_v1_trustline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustSet) ProtoMessage() {}

func (x *TrustSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_trustline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustSet.ProtoReflect.Descriptor instead.
func (*TrustSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_trustline_proto_rawDescGZIP(), []int{0}
}

func (x *TrustSet) GetLimitAmount() *Amount {
	if x != nil {
		return x.LimitAmount
	}
	return nil
}

func (x *TrustSet) GetQualityIn() uint32 {
	if x != nil {
		return x.QualityIn
	}
	return 0
}

func (x *TrustSet) GetQualityOut() uint32 {
	if x != nil {
		return x.QualityOut
	}
	return 0
}

var File_sf_xrpl_type_v1_trustline_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_trustline_proto_rawDesc = "" +
	"\n" +
	"\x1fsf/xrpl/type/v1/trustline.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"\x86\x01\n" +
	"\bTrustSet\x12:\n" +
	"\flimit_amount\x18\x01 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\vlimitAmount\x12\x1d\n" +
	"\n" +
	"quality_in\x18\x02 \x01(\rR\tqualityIn\x12\x1f\n" +
	"\vquality_out\x18\x03 \x01(\rR\n" +
	"qualityOutBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_trustline_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_trustline_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_trustline_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_trustline_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_trustline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_trustline_proto_rawDesc), len(file_sf_xrpl_type_v1_trustline_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_trustline_proto_rawDescData
}

var file_sf_xrpl_type_v1_trustline_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sf_xrpl_type_v1_trustline_proto_goTypes = []any{
	(*TrustSet)(nil), // 0: sf.xrpl.type.v1.TrustSet
	(*Amount)(nil),   // 1: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_trustline_proto_depIdxs = []int32{
	1, // 0: sf.xrpl.type.v1.TrustSet.limit_amount:type_name -> sf.xrpl.type.v1.Amount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_trustline_proto_init() }
func file_sf_xrpl_type_v1_trustline_proto_init() {
	if File_sf_xrpl_type_v1_trustline_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_trustline_proto_rawDesc), len(file_sf_xrpl_type_v1_trustline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_trustline_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_trustline_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_trustline_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_trustline_proto = out.File
	file_sf_xrpl_type_v1_trustline_proto_goTypes = nil
	file_sf_xrpl_type_v1_trustline_proto_depIdxs = nil
}
