// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/xrpl/type/v1/vault.proto

package pbxrpl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VaultCreate - Creates a single-asset vault
// Reference: https://xrpl.org/vaultcreate.html
type VaultCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset the vault holds
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// (Optional) Maximum assets the vault can hold
	AssetsMaximum *Amount `protobuf:"bytes,2,opt,name=assets_maximum,json=assetsMaximum,proto3" json:"assets_maximum,omitempty"`
	// (Optional) Metadata for LP tokens (hex)
	MptokenMetadata string `protobuf:"bytes,3,opt,name=mptoken_metadata,json=mptokenMetadata,proto3" json:"mptoken_metadata,omitempty"`
	// (Optional) Domain ID
	DomainId string `protobuf:"bytes,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// (Optional) Withdrawal policy
	WithdrawalPolicy uint32 `protobuf:"varint,5,opt,name=withdrawal_policy,json=withdrawalPolicy,proto3" json:"withdrawal_policy,omitempty"`
	// (Optional) Data field (hex)
	Data string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// (Optional) Scale for LP tokens
	Scale         uint32 `protobuf:"varint,7,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultCreate) Reset() {
	*x = VaultCreate{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultCreate) ProtoMessage() {}

func (x *VaultCreate) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultCreate.ProtoReflect.Descriptor instead.
func (*VaultCreate) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *VaultCreate) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *VaultCreate) GetAssetsMaximum() *Amount {
	if x != nil {
		return x.AssetsMaximum
	}
	return nil
}

func (x *VaultCreate) GetMptokenMetadata() string {
	if x != nil {
		return x.MptokenMetadata
	}
	return ""
}

func (x *VaultCreate) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *VaultCreate) GetWithdrawalPolicy() uint32 {
	if x != nil {
		return x.WithdrawalPolicy
	}
	return 0
}

func (x *VaultCreate) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *VaultCreate) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// VaultSet - Updates a vault
// Reference: https://xrpl.org/vaultset.html
type VaultSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// (Optional) New maximum assets
	AssetsMaximum *Amount `protobuf:"bytes,2,opt,name=assets_maximum,json=assetsMaximum,proto3" json:"assets_maximum,omitempty"`
	// (Optional) New domain ID
	DomainId string `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// (Optional) New data field (hex)
	Data          string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultSet) Reset() {
	*x = VaultSet{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSet) ProtoMessage() {}

func (x *VaultSet) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSet.ProtoReflect.Descriptor instead.
func (*VaultSet) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *VaultSet) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultSet) GetAssetsMaximum() *Amount {
	if x != nil {
		return x.AssetsMaximum
	}
	return nil
}

func (x *VaultSet) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *VaultSet) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// VaultDelete - Deletes a vault
// Reference: https://xrpl.org/vaultdelete.html
type VaultDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID to delete
	VaultId       string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDelete) Reset() {
	*x = VaultDelete{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDelete) ProtoMessage() {}

func (x *VaultDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDelete.ProtoReflect.Descriptor instead.
func (*VaultDelete) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *VaultDelete) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

// VaultDeposit - Deposits assets into a vault
// Reference: https://xrpl.org/vaultdeposit.html
type VaultDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// Amount to deposit
	Amount        *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDeposit) Reset() {
	*x = VaultDeposit{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDeposit) ProtoMessage() {}

func (x *VaultDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDeposit.ProtoReflect.Descriptor instead.
func (*VaultDeposit) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *VaultDeposit) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultDeposit) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// VaultWithdraw - Withdraws assets from a vault
// Reference: https://xrpl.org/vaultwithdraw.html
type VaultWithdraw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// Amount of LP tokens to burn
	Amount *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// (Optional) Destination for withdrawn assets
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	// (Optional) Destination tag
	DestinationTag uint32 `protobuf:"varint,4,opt,name=destination_tag,json=destinationTag,proto3" json:"destination_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VaultWithdraw) Reset() {
	*x = VaultWithdraw{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWithdraw) ProtoMessage() {}

func (x *VaultWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWithdraw.ProtoReflect.Descriptor instead.
func (*VaultWithdraw) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{4}
}

func (x *VaultWithdraw) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultWithdraw) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *VaultWithdraw) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *VaultWithdraw) GetDestinationTag() uint32 {
	if x != nil {
		return x.DestinationTag
	}
	return 0
}

// VaultClawback - Claws back tokens from a vault holder
// Reference: https://xrpl.org/vaultclawback.html
type VaultClawback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// Holder to claw back from
	Holder string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// (Optional) Amount to claw back
	Amount        *Amount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultClawback) Reset() {
	*x = VaultClawback{}
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultClawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultClawback) ProtoMessage() {}

func (x *VaultClawback) ProtoReflect() protoreflect.Message {
	mi := &file_sf_xrpl_type_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultClawback.ProtoReflect.Descriptor instead.
func (*VaultClawback) Descriptor() ([]byte, []int) {
	return file_sf_xrpl_type_v1_vault_proto_rawDescGZIP(), []int{5}
}

func (x *VaultClawback) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultClawback) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *VaultClawback) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_sf_xrpl_type_v1_vault_proto protoreflect.FileDescriptor

const file_sf_xrpl_type_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x1bsf/xrpl/type/v1/vault.proto\x12\x0fsf.xrpl.type.v1\x1a\x1csf/xrpl/type/v1/amount.proto\"\x9a\x02\n" +
	"\vVaultCreate\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.sf.xrpl.type.v1.AssetR\x05asset\x12>\n" +
	"\x0eassets_maximum\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\rassetsMaximum\x12)\n" +
	"\x10mptoken_metadata\x18\x03 \x01(\tR\x0fmptokenMetadata\x12\x1b\n" +
	"\tdomain_id\x18\x04 \x01(\tR\bdomainId\x12+\n" +
	"\x11withdrawal_policy\x18\x05 \x01(\rR\x10withdrawalPolicy\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x14\n" +
	"\x05scale\x18\a \x01(\rR\x05scale\"\x96\x01\n" +
	"\bVaultSet\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12>\n" +
	"\x0eassets_maximum\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\rassetsMaximum\x12\x1b\n" +
	"\tdomain_id\x18\x03 \x01(\tR\bdomainId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"(\n" +
	"\vVaultDelete\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\"Z\n" +
	"\fVaultDeposit\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\"\xa6\x01\n" +
	"\rVaultWithdraw\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12/\n" +
	"\x06amount\x18\x02 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amount\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12'\n" +
	"\x0fdestination_tag\x18\x04 \x01(\rR\x0edestinationTag\"s\n" +
	"\rVaultClawback\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12/\n" +
	"\x06amount\x18\x03 \x01(\v2\x17.sf.xrpl.type.v1.AmountR\x06amountBAZ?github.com/xrpl-commons/firehose-xrpl/pb/sf/xrpl/type/v1;pbxrplb\x06proto3"

var (
	file_sf_xrpl_type_v1_vault_proto_rawDescOnce sync.Once
	file_sf_xrpl_type_v1_vault_proto_rawDescData []byte
)

func file_sf_xrpl_type_v1_vault_proto_rawDescGZIP() []byte {
	file_sf_xrpl_type_v1_vault_proto_rawDescOnce.Do(func() {
		file_sf_xrpl_type_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_vault_proto_rawDesc), len(file_sf_xrpl_type_v1_vault_proto_rawDesc)))
	})
	return file_sf_xrpl_type_v1_vault_proto_rawDescData
}

var file_sf_xrpl_type_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sf_xrpl_type_v1_vault_proto_goTypes = []any{
	(*VaultCreate)(nil),   // 0: sf.xrpl.type.v1.VaultCreate
	(*VaultSet)(nil),      // 1: sf.xrpl.type.v1.VaultSet
	(*VaultDelete)(nil),   // 2: sf.xrpl.type.v1.VaultDelete
	(*VaultDeposit)(nil),  // 3: sf.xrpl.type.v1.VaultDeposit
	(*VaultWithdraw)(nil), // 4: sf.xrpl.type.v1.VaultWithdraw
	(*VaultClawback)(nil), // 5: sf.xrpl.type.v1.VaultClawback
	(*Asset)(nil),         // 6: sf.xrpl.type.v1.Asset
	(*Amount)(nil),        // 7: sf.xrpl.type.v1.Amount
}
var file_sf_xrpl_type_v1_vault_proto_depIdxs = []int32{
	6, // 0: sf.xrpl.type.v1.VaultCreate.asset:type_name -> sf.xrpl.type.v1.Asset
	7, // 1: sf.xrpl.type.v1.VaultCreate.assets_maximum:type_name -> sf.xrpl.type.v1.Amount
	7, // 2: sf.xrpl.type.v1.VaultSet.assets_maximum:type_name -> sf.xrpl.type.v1.Amount
	7, // 3: sf.xrpl.type.v1.VaultDeposit.amount:type_name -> sf.xrpl.type.v1.Amount
	7, // 4: sf.xrpl.type.v1.VaultWithdraw.amount:type_name -> sf.xrpl.type.v1.Amount
	7, // 5: sf.xrpl.type.v1.VaultClawback.amount:type_name -> sf.xrpl.type.v1.Amount
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sf_xrpl_type_v1_vault_proto_init() }
func file_sf_xrpl_type_v1_vault_proto_init() {
	if File_sf_xrpl_type_v1_vault_proto != nil {
		return
	}
	file_sf_xrpl_type_v1_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_xrpl_type_v1_vault_proto_rawDesc), len(file_sf_xrpl_type_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_xrpl_type_v1_vault_proto_goTypes,
		DependencyIndexes: file_sf_xrpl_type_v1_vault_proto_depIdxs,
		MessageInfos:      file_sf_xrpl_type_v1_vault_proto_msgTypes,
	}.Build()
	File_sf_xrpl_type_v1_vault_proto = out.File
	file_sf_xrpl_type_v1_vault_proto_goTypes = nil
	file_sf_xrpl_type_v1_vault_proto_depIdxs = nil
}
